### ISSUE TITLE
Plugins listing

### ISSUE THREAD

**Issue by billymoon** [andrewplummer/Sugar#296]
It is so easy to extend Sugar, I have written several module style things for my own use. I imagine if there was a central place to share them, there could be lots more people contributing.

I imagine things like obscure parsers, for chess PGN files for example. Or a whole host of things that should never be included in the core, but could be useful as modules. I am sure there are lots out there, but impossible to find.

**Comment by andrewplummer** [comment]
I have now officially taken 3.5 years to respond to this issue. Not proud of it. tl;dr Sugar 2.0.0 has taken forever to get released, and I've taken another few months to finally get around to my issues. The new version now has much improved support for plugins. I have created a boilerplate repo for creating plugins that I will be referring everyone too. In the readme there I recommend naming any sugar plugin with `sugar-`, and have set it up to be readily deployed to npm and bower. I would like to leverage both these systems as the official way to create and share Sugar plugins, and searching `sugar-` should allow people to search what's available.

If anyone is still listening I hope that this helps, although I'm sure you've long since moved on...

**Comment by billymoon** [comment]
btw - I think bower has had it's day: https://www.google.co.uk/trends/explore?q=npm%20install,bower%20install

<img width="865" alt="screen shot 2016-12-04 at 17 08 51" src="https://cloud.githubusercontent.com/assets/858868/20868032/89c5b7a8-ba49-11e6-9260-f445ff8b5c3a.png">

**Comment by andrewplummer** [comment]
Maybe... I've noted that component.io has dropped off the map completely, so is no longer supported by Sugar, however bower is easy enough to support for the time being. If something new comes on the scene it may be supported as well... this is something that will just have to change as the landscape changes.
