### ISSUE TITLE
Add method to convert and array to a "set"

### ISSUE THREAD

**Issue by kevincox** [andrewplummer/Sugar#300]
It is often useful to convert an array to a "set", an object with keys of the elements and values of `true` (or anything) so that you can do quick look ups.

```js
var good = ["p", "span", "br", "img"].set();
function isSafe(ele)
{
  return good[ele] || false;
}
```

**Comment by andrewplummer** [comment]
OK I think I don't need to point out the ridiculous delay in following up on this issue. Sorry about that. I've flagged this as "plugin", but I think I'm going to remove that label and close this one.

You're free to create a plugin (if you even care anymore) for this, and 2.0.0 is going to make it very easy to do that, but I feel that this one now treads on the territory of ES6 sets (which I believe weren't even drafted when this issue was posted anyway), so I would recommend getting [a polyfill](https://github.com/medikoo/es6-set) for that instead.

Anyway thanks again and sorry for the delay!
