### ISSUE TITLE
Number.bytes() doesn't return the correct suffix

### ISSUE THREAD

**Issue by Carpetsmoker** [andrewplummer/Sugar#369]
```
>>> 1000..bytes(6)
"0.976563kB"
>>> 1024..bytes(6)
"1kB"
>>> 1000000..bytes(6)
"0.953674MB"
>>> 1048576..bytes(6)
"1MB"
```

As you can see by these examples, technically, it should return "1KiB" and "1MiB"

Perhaps through an option or separate function? (even though MB is always `wrong' in a technical sense, some people might prefer it ...)

Thanks :-)

**Comment by andrewplummer** [comment]
Ok I'm really stretching the definition of "forever" here. This will finally be going out in v2.0.0. The method signature in the end will be `precision`, `si`, `units`. If `si` is true, the base will be 1000 instead of 1024. Additionally `units` is a notation for describing both which units to use and also the range. Will have a section in the docs about how to customize, but long story short for `KiB` you want to do this:

```
n.bytes(0, false, '|,Ki,Mi,Gi,Ti,Pi,Ei');
```

This will produce the units you're expecting.

**Comment by andrewplummer** [comment]
One more change, `binary` can serve as a shortcut to the above, so all you have to do is:

```
n.bytes(0, false, 'binary');
```

**Comment by andrewplummer** [comment]
Ok this was finally release with 2.0.0, so closing!
