### ISSUE TITLE
String.normalize() call causes "Uncaught illegal access" exception in Chrome 34

### ISSUE THREAD

**Issue by onlyurei** [andrewplummer/Sugar#417]
After upgrading to Chrome 34, when trying to call String.normalize(), it throws an "uncaught illegal access" exception, looks like this method became a privileged native implementation in Chrome 34.

**Comment by CyborgMaster** [comment]
I'm having the same error in Chrome.  I have to abandon `parameterize()` completely and roll my own version due to the error (it even crashes on the current SugarJS API docs page).  As `parameterize()` is currently completely broken in Chrome, how long do you think it might before we see a release where it is working again?

**Comment by andrewplummer** [comment]
@CyborgMaster I think now I can confidently say that the answer is "far too long". Very large release coming soon... if you're even still alive...

**Comment by andrewplummer** [comment]
Ok, well it's been nearly as long again, but this release has gone out! Hopefully you've checked back with the site and discovered for yourself (and are even still interested) but if not... tada!

At any rate `normalize` has been removed and will not be causing problems again. The scope of the method was pretty much outside what Sugar should be doing anyway.

FYI for issues like this in the future, Sugar 2.0.0 now has both the ability to be used without extending methods as well as the ability to exclude methods by name if they are causing issues. In this case it would be:

``javascript
Sugar.extend({
  except: ['normalize']
});
```

Hopefully this won't be required for any other methods, but good to know it's there. Thanks for this!

**Comment by CyborgMaster** [comment]
Thanks for taking the time to respond to this old issue.  It's much appreciated.  I've been watching Sugar closely, and we still use it every day.  I'm very excited for the 2.0 release, but haven't found the time to upgrade yet.  

So just curious:  I ran into this problem originally because `parameterize` used `normalize` under the hood.  You say `normalize` has been removed, so does `parameterize` still do something to remove the non-ascii characters?

Thanks for all your hard work!

**Comment by andrewplummer** [comment]
When you're ready to upgrade have a look [here](https://sugarjs.com/upgrading). This will help ease the pain.

So, `parameterize` now does not touch non-ascii characters, either by normalizing or removing them, it's basically now only for special punctuation characters that won't render in a URL. IMHO this is a much better solution for the method as it allowed it to be moved into the default String module without all the extra baggage. Having Sugar handle full blown normalization across all languages was kind of ridiculous to be honest, and use cases will likely range from replacing a few simple specific characters, to a simple language that only has a few characters anyway (both cases that a simple `replace` could easily handle), to simple handling of a small subset of languages, to all-out [Unicode decomposition](https://en.wikipedia.org/wiki/Unicode_equivalence). In these extreme cases, either using a library or leaving it up to [native browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) if you have the option is highly preferable. Having Sugar do this half-assed wasn't helping anyone and was bloating the library with characters that don't minify or compress well.

**Comment by CyborgMaster** [comment]
Thanks for the explanation.  That makes a lot of sense, and I'm totally on board.
