### ISSUE TITLE
abbreviateNumber with custom thousands and decimal character

### ISSUE THREAD

**Issue by marcalj** [andrewplummer/Sugar#422]
There's a way to globally set thousands and decimal character, or at least provide one when calling `(3232).metric(1, 2);` ??

Thanks.

**Comment by andrewplummer** [comment]
Ok, I hope you've had some way to get other updates because it sure wasn't through this ticket... Sugar 2.0.0 has been out for a while now, and the changes here have been reflected. Setting the option will be:

```javascript
Sugar.Number.setOption('thousands', ' ');
Sugar.Number.setOption('decimal', ',');
```

More information about how this feature works is [here](https://sugarjs.com/docs/#/Accessors).
