### ISSUE TITLE
Object.merge, Object.clone and String.has in 1.5.0

### ISSUE THREAD

**Issue by ermouth** [andrewplummer/Sugar#426]
Right now I have 200K+ sloc js codebase built on top of Sugar 1.4.x. This code is running in production for 260К+ users. And this code use `Object.merge` and `Object.clone` extensively.

Changes made in these methods in 1.5 surely lead me – if I wanted to use them – to rewrite, not just refactor, all the code. Also we’ll need to retest it thoroughly.

Cost of these ops is absolutely enormous.

So there are three options for me in this situation if I want to use Sugar in versions 1.5+:
- ask Andrew to rethink
- ask to add backward-compatible aliases
- fork Sugar

May be I’m too late, but I think deep backward incompatibility is a serious issue worth to discuss.

Also I think there is no reason to remove `String.has` – it has clean unique syntax and is shorter than `.contains`. I see no conflict if `.has` coexisted with `.contains`.

What do you think?

**Comment by andrewplummer** [comment]
OK, this issue is more than a year old and a lot has changed. First of all very sorry for the delay. I'll try to summarize.

First, the next version of Sugar is going to be `2.0.0`. Much will change, the most major being that extending prototypes will now be opt-in. So, to first address the spirit in which this issue was raised, I'm not sure that I can promise you will be happy. Sugar will be moving forward and that means some big changes. However, one of my bigger todos is to go through all open bugs and make sure that they are also merged back into 1.4 where applicable. I will do my best to stay on top of bugs in both trunks (better than I have so far) so that you can continue to use 1.4 for as long as is possible/reasonable. If support for 1.4 is ever dropped I will also try to make sure it's known/anticipated. So, on to the details:

### Object.merge

I have opened up ticket #518 to discuss `Object.merge` on it's own. To summarize that ticket (and address the points about it here):

#### `null` as a value

You are absolutely correct that `null` is itself a value. So much time has passed that I'm confusing myself as to what was the real issue here but `1.4.1` treats `null` like any other defined value and `2.0.0` will also do so. If this ever becomes not true then it's a bug.

#### Array-merging and non-enumerable properties

I still want to support non-enumerable properties when merging, but I have now seen the light. You were 100% correct and I agree that this is unexpected and undesirable as a default. `Object.merge` without any options/arguments should be as simple (and ideally nearly as performant) as:

```
for (var key in source) {
  if (source.hasOwnProperty(key)) {
    target[key] = source[key];
  }
}
```

Along with the addition of merging property descriptors, I want to expand the options to object merge to 4 and turn it into an options object instead of 4 long arguments to the method. But essentially everything will be off by default (I've also spent a long time trying to optimize the code paths so that checking these options will not hinder performance as well) so that you get a very predictable merge unless you specifically turn these options on. Your example: `Object.merge([{a:1},{a:2}, undefined, {a:4}], [{b:2}, {a:100}, {a:3}], true)` works exactly as you expected.

### Custom resolver

I am still standing by this decision, but I think I may have solved the problem you had and made it more straightforward at the same time. In 2.0.0 the custom resolver will be stopped only if a value that is not undefined is returned. If the function returns undefined, then the merge will be handled as it normally would, including going deeper into the object (when `deep` is `true`). This is more in line with `Object.merge` itself (`undefined` values are not merged, and treated differently from defined values) and also happens to be aligned with Lodash's `customizer` in `_.merge`, and I feel that it makes more sense as it lets you jump in as needed to handle special-case conflicts. So for example (taken from the unit tests and using the new proposed syntax):

```
var o1 = {
  user: {
    firstName: 'Darth',
    lastName: 'Vader',
    helmetSize: 22,
    likes: 2
  }
}
var o2 = {
  user: {
    firstName: 'Luke',
    lastName: 'Skywalker',
    handSize: 15,
    likes: 4
  }
}
var fn = function(key, targetVal, sourceVal) {
  if (key === 'likes') {
    return targetVal + sourceVal;
  }
}
Object.merge(o1, o2, { deep: true, resolve: fn }); ->
{
  user: {
    firstName: 'Luke',
    lastName: 'Skywalker',
    helmetSize: 22,
    handSize: 15,
    likes: 6
  }
}
```

So, only in the case of `likes` will it add together, everything else returns undefined, so it's handled as normally, including going deep. This way you should not ever have to use `Object.merge` inside itself. 


### String#has

The ES6 spec is now finalized and this has become `String#includes`. Sugar's goal is still to stay in line with this, so in `2.0.0` it will polyfill `includes` when it does not exist, including the behavior of throwing an error on a regex. `String#has` will be gone.

However! The string package will also enhance `includes` by default to allow regexes to be passed into the same method. Sugar actually does this kind of behavior already, for example `map('property')` as a shortcut for creating a mapping function. In the case of `includes`, passing a regex will simply call `.test` on the string.

This ability to "enhance" methods is something that Sugar has done for a while now. It only does this in situations where the native method would otherwise throw an error. However, I understand that this behavior may still be undesirable or controversial. Now that `2.0.0` makes prototype extension opt-in, there are options if you want to turn enhancing on or off:

```
Sugar.extend({
   enhance: false
});
```

It's as simple as that. Note that extending `Object.prototype` will also be the same (off by default, but can be turned on with a flag). If you don't feel comfortable overriding ES6 behavior, then even if you turn enhancing off you can still access the method through the global by doing `Sugar.String.includes('subject', /test/)`.

> With all my respect it’s really hard to convince you – as far as I remember it took 4 days when I tried first

Well this time it only took 1 1/2 years :)

**Comment by ermouth** [comment]
Well, since prettypleasing you about `.has` seems not an option, I gonna just get drunked as a swine when you kill it ) But.. maybe... small humble checkbox somewhere at the bottom of ‘Custom build’ page, m? 

> off by default, but can be turned on with a flag

Why not on? Isn‘t it more natural for the lib, that extends things?

> Well this time it only took 1 1/2 years :)

That‘s ok, happy you moving things on )

**Comment by andrewplummer** [comment]
> I gonna just get drunked as a swine when you kill it ) But.. maybe... small humble checkbox somewhere at the bottom of ‘Custom build’ page, m?

Hahaha the bigger question is are you still going to be using 1.4?? :)
If you are then it will always be there anyway.

But the other question is would you not use `includes` if it's the same functionality? If not why not? If there really is a good use case for aliasing `has` then I would hear it out, but I want it to be something more than "it sounds better" or "it's shorter".

> Why not on? Isn‘t it more natural for the lib, that extends things?

Well in this case I'm talking only about `Object.prototype` being off by default. Turning this on by default can wreak havoc with existing codebases. Imagine people using `for..in` loops with arrays. Actually even that is safe *mostly* because of `Object.defineProperty`, but in my opinion the "mostly" part makes it even LESS safe. What I mean is that imagine Sugar extends `Object.prototype` by default. A user puts it in a codebase and it seems fine, but then they learn their site is breaking in IE8...well it's because there are no non-enumerable properties in IE8 so the `for..in` loops are breaking. If it was me, I'd get pissed off and pull it out immediately. Anyway it's very easy to turn on, but I want to make sure that it's done by a conscious decision.

**Comment by ermouth** [comment]
> are you still going to be using 1.4

For massively used already deployed public centralized systems – yes. We do not touch things that work, for practical reasons. For new deployments I‘d prefer to upgrade.

> But the other question is would you not use `includes` if it's the same functionality?

Well, we surely will make dumb find/replace across centralized codebases, it‘s pretty easy. But I have quite a lot of users of cloudwall, that is decentralized system with IDE onboard and local app cache. Since apps live inside end-users‘ in-browser DBs, I can‘t control them easily, sync does not delivers apps immidiately when user goes online. I just don‘t know what will arrive first, apps or platform.

Re-decentralization of web is new trend, it was not seen even year ago – and this trend bit changes way of thinking on backward-compatibility. If you‘re interested, I can give two real-life scenarios I have, when upgrading even both platform and all apps simultaneously on ‘mother’ server would break things.

Having `.has` alias for `.includes` is quite modest price to make this issues never happen.

> can wreak havoc with existing codebases
> so the for..in loops are breaking

To say, usage of `.hasOwnProperty` became nearly idiomatic inside `for..in`. Although argument is good – I personally had severeal discussions on Sugar, ended up with that piss off about `Object.prototype`, and I saw unbreakable wall trying to argue it‘s not so terrible.

So hope lifting this block could help Sugar to spread more widely. I‘m bit tired to see all these ((())) of lodash here and there, Javascript isn‘t Lisp.

So just do what you think is reasonable. As for our core technology, $.my, I already have several workarounds for IE8 in place, so I‘ll just add one more, not a problem.

**Comment by andrewplummer** [comment]
> that is decentralized system with IDE onboard and local app cache

This is actually really interesting. I'm definitely interested in your use cases but I think I get the nature of the issue now. This seems like a much bigger problem, however... Any major API change will essentially be a big hassle for you, no? Essentially, I see it as being an application specific need for backward-compatibility that is a step above normal.  This is your use case (and probably more people going forward it sounds like) so I think it's fair to consider, however I don't think it's any libraries' responsibility to maintain a perfect level of backward-compatibility forever. That would be impossible (remember though I'm planning to support 1.4 as a minor version, so that's different). Rather I think it would be good if Sugar could provide tools to give as much flexibility as possible so you can retro-fit your application as needed.

Here (hopefully) is an example of this. Among other things, Sugar 2.0.0 is intended to be much more modular. `sugar-core` will be split out into it's own npm package, and will contain a very small amount of code to allow people to write their own methods and bootstrap them (or not depending on their needs) onto native prototypes. It means that people can write Sugar plugins without needing any of the main library (just the core). I get a lot of suggestions for methods that don't make sense to be included in Sugar itself, but the goal is to allow people to still easily make and deploy them in the same ecosystem. Here is how that works:

```
Sugar.Array.defineInstance({
   'crazyFunction':  function (arr, arg1, arg2, ...) { ... }
});
```

This will create a single static method that can be called by `Sugar.Array.crazyFunction(arr, ...)` or, when mapped to the prototype, called as an instance method on an array. This lets people create plugins while still pushing the decision to extend prototypes or not down to the end user, where it should be.

So what does this have to do with you? Well what if we could simply do this:

```
Sugar.String.alias('has', Sugar.String.includes);
```

This would be super simple and I think get you where you need to be? You can also augment or tweak methods with this as well...

> To say, usage of .hasOwnProperty became nearly idiomatic inside for..in.

I really would hope so, but I've seen a lot of bad code out there... I think better than just assuming people will use `hasOwnProperty` better to wait until IE8 truly dies. Unfortunately probably will be a while longer.

> ended up with that piss off about Object.prototype

Yeah... it's actually more of a PR question... `Object.prototype` is simply a bad word these days. Maybe if Sugar becomes huge it can go on by default someday but I think not for a while...

**Comment by ermouth** [comment]
> Any major API change will essentially be a big hassle for you, no?

Actually, no. I just proxy most of em to avoid compatibility issues, and expose own simplified API. $.my covers details for UI-related stuff, also PouchDB is proxied, both to avoid deprecations-related faults and to ensure security, and so on.

But I can‘t proxy Sugar for obvious reasons. `Sugar.String.alias('has', Sugar.String.includes);` looks good although.

> is intended to be much more modular

Oh, I think it would be a mistake, but it‘s a separate topic. 

> but I've seen a lot of bad code out there

We all have seen. If one wants to write bad code (having not enough experience, or for well though reasons) – let him do it. But it‘s also separate topic, more about philosophy )

> better to wait until IE8 truly dies

Well... Yesterday, when we started discussion, I checked out about 1M last requests for counters at newsfeed resources I have access to. I see 2.1%, so it definitely does not want to die.

Off: As for .mergeAll – please, gimme a day, I‘m bit sleepy now, and it requires thinking.

**Comment by andrewplummer** [comment]
OK thanks for giving me a lot to think about.

**Comment by andrewplummer** [comment]
OK I'm going to leave this ticket open until the alias functionality lands.

There are a few parts to this issue. I think I've answered with a combination of addressing your issues directly and giving you workarounds in the meantime.

Lastly, my plan to continue to support 1.4.1 works as a final fallback.

**Comment by andrewplummer** [comment]
Ok this has been out for a while now, so closing.
