### ISSUE TITLE
Date.create is undefined 

### ISSUE THREAD

**Issue by maca** [andrewplummer/Sugar#427]
Either by making a build with only core, date and formats and by importing sugar-full.min.js, the create method for Date is not defined, I am interested in the natural language date parsing

> Date.create
>    undefined

--EDIT

Using sinon fakeTimers restores Date methods and deletes Date.create, following code will break Date.create:

```
  it('should be past due if due has passed', function(){
    clock = sinon.useFakeTimers(new Date(2014,1,1).getTime());
    expect( task.is_past_due ).to.eq(false)
    clock = sinon.useFakeTimers(new Date(2015,1,1).getTime());
    expect( task.is_past_due ).to.eq(true)
    clock.restore();
  });
```

**Comment by andrewplummer** [comment]
Ok, sorry for the huge delay on this. Long story short v2.0.0 is soon to be released and there are a few ways this issue will be mitigated.

First global extension is now opt-in so 1) you will have more control over when the globals are extended and 2) `create` can be reached through the `Sugar` global object. Additionally, I have updated the code to not hold the natives in a closure. This way if a global is hijacked in the way Sinon does, it will become the target instead of the native class. This could potentially cause other bizarre issues but only in the case that the global is hijacked, which is a big problem to begin with. Sinon does it properly because it's the only way what they're doing will work, so it's worth modifying Sugar to play well with them.

Anyway, if you want to use sinon with Sugar as of v2.0.0 you can just do:

```
clock = sinon.useFakeTimers(); 
Sugar.extendAll();
```

Just make sure `extendAll` (or `Sugar.Date.extend`) is after `useFakeTimers`, and it should all work just fine. Tested with latest version `1.17.2`.

Also FYI it's only `useFakeTimers` that's the issue here, the rest of Sinon doesn't hijack globals.

**Comment by andrewplummer** [comment]
Ok, going to close this as 2.0.0 has been released for a while now. Note that `Sugar.extendAll()` is in the end `Sugar.extend()`. However it should offer you the flexibility you need here. Thanks!
