### ISSUE TITLE
Incorrect singularization of multiple words

### ISSUE THREAD

**Issue by btesser** [andrewplummer/Sugar#428]
String.singularize converts:
appendices to appendice (should be appendix)
Platypuses to Platypuse (should be platypus)

**Comment by andrewplummer** [comment]
Sorry this has taken ages. So the Inflector module is taken from the same module in ActiveSupport. It has a number of low-hanging-fruit inflections in the module, but handling all is impossible, so the idea is that it exposes an "Inflector" object so that you can define your own inflections! So if your app really is dealing with "platypus", then you should be able to add it yourself. However the docs make no mention of this now, so I'll update!
