### ISSUE TITLE
Object.fromQueryString doesn't support empty values

### ISSUE THREAD

**Issue by esprehn** [andrewplummer/Sugar#438]
Object.fromQueryString("?foo") => {}
Object.fromQueryString("?foo=1") => {foo:1}

but ?foo&bar is a valid query string, and this pattern is common for flag params.

**Comment by andrewplummer** [comment]
Ok, I did a big rewrite of `fromQueryString` to allow an options object and a "smart mode" which auto-casts values to numbers, etc. It seems that in the course of the rewrite, this issue was handled. However I've added some better unit tests for it.

To summarize, when a value is not passed (either `?foo` or `?foo=`), if smart mode is on the result will be `{foo:null}` ... if it's off (off is essentially something like a simple `split` operation and everything is a string), the result will be `{foo:''}`.

**Comment by andrewplummer** [comment]
This has been released so closing!
