### ISSUE TITLE
Not extending on default?

### ISSUE THREAD

**Issue by mren** [andrewplummer/Sugar#448]
Hi there,

I'm working on a project which could benefit greatly from some features of sugar.js.
However I can't use sugar.js as extending all base types is not welcome.

I would love to use the `Date.create` function from the sugar library. For me it would be fine if I could just do
```javascript
var sugar = require('sugar'); // would not overwrite anything
var date = sugar.Date.create('now'); // can be used with the prefix as before
Date.create // undefined
sugar.extendNativeObjects() // behaviour as before
Date.create // [Function]
sugar.extendNativeDate(Date) // or even more fine grained
```
Extending/Modifying every core object of your project is a hard decision to take. Not forcing this decision could perhaps increase the adaption of sugar in JavaScript projects.

I did not find any tickets regarding this topic. Perhaps I didn't search good enough. I only found a discussion at discourse, where they [want to move away from sugar because of the added complexity](https://meta.discourse.org/t/getting-rid-of-sugar-js/7146).

**Comment by andrewplummer** [comment]
Ok guys... lots of delays here but part of that is just to be sure it's done right.

At the point of my last post this was being "planned", but now it's mostly complete. A lot of loose ends to tie up so the release will take a little while longer, but the good news is that the hard part is essentially finished.

Extending prototypes will now be opt in and there will be 2 ways to do it:
```
require('sugar')();
require('sugar').extend();
```

the `()` version is for npm, which returns the Sugar "global" object as the `exports`. The `extend` method mostly exists for the browser, which exposes a global, but also for more explicitness.

Every method defined will have a static version that exists on the exported `Sugar` (on a namespace representing its type, for example `Sugar.Array` for arrays, etc) global and can be called a-la Underscore, and an instance version that will be extended to prototypes when called.
The `Sugar.extend()` method will map every defined method onto it's associated native prototype *except* for `Object.prototype`, which requires being explicitly opted into by passing a flag: `Sugar.extend(true)`.

It should also be mentioned that this change will NOT have functionality akin to Underscore's `chain` method as implied in @mren's second example. This is intentional. I actually did a major rewrite in attempt to get this to work well before reverting everything. The devil is in the details, but in the end it simply could not be done in a performant, clean way, and should be avoided.

This is not only a huge change but was also a major rewrite, so the version will now be `2.0.0`.

I'm going to close this bug out as this is the major feature for this major release, so I'm not going to forget it ;)

Thanks to everyone for their opinions here and also for being so patient. Just a bit more patience, please!

**Comment by vendethiel** [comment]
:+1: keep up the good work :)
