### ISSUE TITLE
Bower not reflecting latest version (1.5.0)

### ISSUE THREAD

**Issue by christydennison** [andrewplummer/Sugar#454]
The bower.json has 1.4.1, not 1.5.0, which is the latest release. Please update the file to reflect the latest release.

**Comment by andrewplummer** [comment]
ok so "very soon" doesn't always live up... a lot has been changing though and `1.5.0` is now `2.0.0`. Sorry about the inconsistency as well as the delays. A lot of changes have been going on and among them are much better build tools, which among other things will build multiple releases to keep everything in line. I also made a checklist for myself... sounds dumb but it's probably the # 1 took to handle stuff like this. 

In the meantime I quickly created a `1.4.1` Github release to keep this inline with bower. Source is still `1.5.0` right now but this was never published. I think it makes sense for edge files to be set to the next coming milestone so these will immediately change to `2.0.0`. Going forward everything will be published at the same time.

Thanks for your continued patience!

**Comment by lolmaus** [comment]
@andrewplummer, is the roadmap public? Very curious of what the differences are between 1.4, 1.5 and 2.0.

**Comment by andrewplummer** [comment]
First note that 1.5 is off the table now. It was never released. The changes were major enough that this has now gone directly to 2.0.

The best "roadmap" at the moment is the [cautionlog](https://github.com/andrewplummer/Sugar/blob/master-2.0.0/CAUTION.md) which I publish as a kind of vetted changelog, sorted by the most major/breaking changes to the API. See the [changelog](https://github.com/andrewplummer/Sugar/blob/master-2.0.0/CHANGELOG.md) as well for more detailed changes.

By far the most major change (and the point of the entire release) is that prototype extension will now be opt-in instead of enabled by default. Many other changes including how npm packages will work are now a result of this major change.
