### ISSUE TITLE
Implement some methods from python's itertools

### ISSUE THREAD

**Issue by eric-wieser** [andrewplummer/Sugar#458]
As a pythonista at heart, I miss `.groupby` and `.starmap`. I'm not sure what the best way of fitting these into the API is, but here're the implementation:

```javascript
Array.extend({
	// Behaves like itertools.groupby, maintaining sort order
	orderedGroupBy: function(map) {
		var keys = this.map(map);

		var group;
		var lastKey = function sentinel(){};
		var overall = [];
		this.each(function(el, index) {
			var key = keys[index];

			// no previous data for this key
			if(!Object.equal(key, lastKey)) {
				group = [];
				overall.push([key, group]);
			}

			group.push(el);
			lastKey = key;
		});

		return overall;
	},

	starMap: function(fn, context) {
		return this.map(function(el) {
			return fn.apply(context, el);
		});
	}
});
```

Letting you do something like

```javascript
>>> var data = [{a:1, b:2}, {a:1, b:3}, {a:2, b:3}, {a:1, b:4}]
>>> grouped = data.orderedGroupBy('a')
[[1,  [{a:1, b:2}, {a:1, b:3}]], [2,  [{a:2, b:3}], [1,  [{a:1, b:4}]]]
>>> grouped = data.starMap(function(key, values) {
    console.log(key, value.map('b'));
})
1 [2, 3]
2 [3]
1 [4]
```

**Comment by andrewplummer** [comment]
Hi... thanks for this ticket and really sorry for taking a billion years to respond to you. Really should have got back a lot sooner. So, Sugar has a [`groupBy`](http://sugarjs.com/api/Array/groupBy) method that's hopefully something like what you're looking for. Actually looking at your example I'm a little confused why `1` is in two separate groups. At any rate it will return an object whose keys are the keys to the unique grouping. For `starMap` you could simply do `Object.map` on the object returned by `groupBy`.

Hope this works for you!

Thanks and sorry again for the delay.

**Comment by eric-wieser** [comment]
The one being in two separate groups is a key feature of this implementation - it's aim is to only group together adjacent entries in the input list. This is the behavour of `itertools.groupby`.

Starmap takes a list of lists, and applies a function to each sublist, passing one element per argument. So:
```
[[1, 2, 3], [4, 5, 6]].starmap(f) == [f(1, 2, 3), f(4, 5, 6)]
```

**Comment by eric-wieser** [comment]
Perhaps `s[readMap`, given the equivalent is the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)

**Comment by andrewplummer** [comment]
I think I see now... So `itertools.groupby` is essentially the same as Sugar's `groupBy` with the exception that rather than aggregating all groups by a key, it iterates through the array and creates a grouping whenever the key changes.

`starmap` appears to be a way to map an array treating each element in the array as an argument list that is passed to a function.

Let me know if that's not right...

I have to be honest, it's very hard to think of a use case for this that would not end up being more confusing to read, unless you're a Pythonista.

For example:

```
arr.map(function(args) {
   return f.apply(this, args);
});
```

Would be much easier to understand, and I don't think it's a question of naming. Something on `Function` itself would be a bit better home for this, such as:

```
f.applyAll(arr);
```

But even in this case I don't think it's quite there. This seems like one of those cases where the clarity of writing out a function to `map` would be a lot better I think.

As for `groupby` I think the use-case is even more obscure. The python docs themselves mention that "it is usually necessary to have sorted the data using the same key function", which I would acknowledge as meaning that an operation like `groupBy` is a more common use case.


One of the goals of the next version of Sugar (v2.0.0) is to make it much easier to augment Sugar and add your own methods. Essentially the "core" will exist as a standalone module that allows you to define methods that can then be extended onto prototypes by the end user. I think this is a perfect candidate for hooking into that system. Having a Python-like plugins "group" would be very nice, and if it turns out that people really do love `groupby` and `starmap` then it could be considered to be added to the main build.

**Comment by andrewplummer** [comment]
So I'm going to close this one out for now. 2.0.0 will be released hopefully very soon. There will be detailed information in the docs about how to author your own plugin and I'm also planning on having a link to a separate repo with a plugin template as well, so please check back! Thanks.
