### ISSUE TITLE
Date.utc.create doesn't return correct date when the there's GMT timezone indication on the string

### ISSUE THREAD

**Issue by alFReD-NSH** [andrewplummer/Sugar#464]
```
> Date.utc.create('Sun Oct 21 2012 00:00:00 GMT+0000').iso()
'2012-10-21T03:00:00.000Z'
```

I expected it to be `'2012-10-21T00:00:00.000Z'` because `Sun Oct 21 2012 00:00:00 GMT+0000` that's what the date means to me. 

Note the my timezone is `GMT+0300`

**Comment by andrewplummer** [comment]
Hi, really sorry to take so damn long to get back on such a simple issue.
This actually is correct, but I see how it's confusing. Please have a look at the explanation in #512, and I welcome any suggestions to make this clearer.

Your bug was first but I'm going to close this one just because I already responded to the other first. Thanks for your patience!
