### ISSUE TITLE
March 8, 2015, 9:00am PDT is the Hour of Apocalypse (apparently)

### ISSUE THREAD

**Issue by dglazkov** [andrewplummer/Sugar#468]
See http://jsbin.com/fuparuxuvaci/1/edit

No matter how much you try, you can't advance past this date. Freaky stuff. I am driving to the store right now to buy canned goods and guns :smiley:

Found this when using `Range.every` -- it was just hanging mysteriously. Turns out, it uses `advance` internally, and ended up looping forever.

**Comment by andrewplummer** [comment]
Hi, very sorry to take so long to address this! I will definitely have a look!

**Comment by andrewplummer** [comment]
Note that #470 is likely a duplicate.

**Comment by andrewplummer** [comment]
Hi... I'm taking a look at this now and it's a bit weird. I haven't been able to confirm the test cases you set up... can you confirm if they're still breaking?

What I have determined is this. Let's say you're 15 minutes away from going *on* DST (assuming [Pacific Time](http://www.timeanddate.com/time/change/usa/los-angeles) but not parsing as a string -- that seemed to be skewing your tests):

```
var d1 = new Date(2015, 2, 8, 1, 45);
var d2 = new Date(d1.getTime() + (15 * 60 * 1000));
var d3 = new Date(d1);
d3.setMinutes(60);
```

Both `d2` and `d3` will be exactly 15 minutes ahead of `d1`, or `March 8, 2015 3:00am`, as once it hits 2am the clocks will skip ahead to 3am. If you are 15 minutes away from coming *off* DST, then:

```
var d1 = new Date(2015, 10, 1, 1, 45);
var d2 = new Date(d1.getTime() + (15 * 60 * 1000));
```

Again, `d2` will be exactly 15 minutes ahead of `d1` which is in this case `November 1, 2015 1:00 am`, as the clocks are set back. However!

```
var d1 = new Date(2015, 10, 1, 1, 45);
var d3 = new Date(d1);
d3.setMinutes(60);
```

`d3` is now `November 1, 2015 2:00am`, or 1 hour and 15 minutes ahead of `d1`.

The reason appears to be that `setMinutes` and other `set` methods are simply trying to set to a time that can exist. It's the difference between saying "set to a time that is 15 minutes ahead of November 1, 1:45am" and "set to a time that has the year set to 2015, the 11th month, 1st day, 1 hour and 60 minutes`. `60` would then go on to set the `hours` to `2`, but since this date actually is possible, it sets it and skips ahead an unintentional hour.

Back in March, there literally *IS* no `2:00am` on `March 8th, 2015` in Pacific Time, so the date must get pushed ahead.

This is a very tricky situation to be in. There are a ton of other edge cases that are handled by using the `set` methods, as they are designed to overshoot a date. I'm not entirely sure how to handle this but I think one place to start is to see if the timezone offset has changed and workaround accordingly....

**Comment by andrewplummer** [comment]
Ok, this should be fixed now. I'll spare you the gory details but the long and short of it is that if you're adding anything "hours" and below to a date, you MUST do it by adding an absolute time and not the `setHours` method. The reason is that anything but absolute time is by definition vague due to DST shifts. Adding to a date is subtly different from creating a date in this way...
