### ISSUE TITLE
Feature Request: Set/Get Object with 'Dot Notation'

### ISSUE THREAD

**Issue by DylanPiercey** [andrewplummer/Sugar#472]
```
var setProp = function (obj, path, val) {
    path = path.split('.');

    for (var i = 0, max = path.length - 1; i < max; i += 1) {
        obj = obj[path[i]] = obj[path[i]] || {};
    }

    obj[path[i]] = val;
};

var getProp = function (obj, path) {
    path = path.split('.');

    for (var i = 0, max = path.length; i < max; i += 1) {
        obj = obj[path[i]];
    }

    return obj;
};
```

Which (when extending Object) would let us do:

```
var obj = {};
Object.setProp(obj, 'location.address.street', 'test');
console.log(obj.location.address.street); // -> test
```

And retrieve it dynamically with this:

```
console.log(Object.getProp(obj, 'location.address.street')); // -> test
```

**Comment by andrewplummer** [comment]
Hm... this existed (sort of) previously as String#namespace but was removed as it wasn't particularly useful, however it wasn't as well thought out.

I can see the usefulness of this, but I'll have to think on it a bit.

Another alternative might be something like:
```
Object.namespace(key); // Getter
Object.namespace(key, value); // Setter
```

**Comment by andrewplummer** [comment]
Sorry last comment (which was ages ago) should of course include the object as well:

```
Object.namespace(obj, key);
Object.namespace(obj, key, value);
```

However thinking about it maybe your original naming was better, or even simpler:
```
Object.get(obj, key);
Object.set(obj, key, value);
```

However I'm still wondering if this would be useful enough to most people to be added. What do you think? Is this something you'd still like to see?

**Comment by vendethiel** [comment]
Well, it's a use case that pops up once in a while. not that often, but definitely happened

**Comment by andrewplummer** [comment]
OK... will think about this one. I'm inclined to like it but does have some implications that need to be ironed out.

**Comment by DylanPiercey** [comment]
In lodash every "pick" style function such as "_.map(arr, 'key')" works with dot notation getters.

**Comment by andrewplummer** [comment]
That is interesting. I'm inclined to think that this should work in Sugar as well. However it's a bit tangential to the topic, which is asking to expose this functionality in the public API.

Also there is a subtle nuance here:

```
_.map([{'foo': { 'bar': 3 }}], 'foo.bar');
```

vs

```
_.map([{'foo.bar': 4}], 'foo.bar');
```

These kind of nuances can be tricky.

**Comment by vendethiel** [comment]
They very much are... That's why lenses are such a big topic as well :P. not really relevant for Sugar, I guess, though.

**Comment by andrewplummer** [comment]
What's lenses?

**Comment by vendethiel** [comment]
Functional "equivalent" to getter/setter (where everything is pure, i.e. you need to copy the structure "deeply"). you're supposed to be able to compose them and all. Far too complex and totally unrelated to Sugar, but they're the de-facto solution to deep getter/setter stuff in languages like Haskell, etc.

**Comment by andrewplummer** [comment]
Interesting... will have a look just for reference... thanks!

**Comment by andrewplummer** [comment]
Ok, so I'd like to update my thinking on this issue. Although I somewhat suggested it above, I feel that the naming `get` and `set` are too general considering the following problem:

```
var obj = {
  foo: {
    bar: 1
  },
  'foo.bar': 2
}
Object.get('foo.bar');  // Should this be 1 or 2??
```

I think that this method's naming should make it explicit about what it's doing. For the same reason I think it should also be a single method that does both get and set rather than two different methods, as that would be more clear. Right now in my mind the following might work:

- `namespace` (the original name)
- `dot`
- `deep`

I'm open to new naming ideas as well.  Additionally, this method can be flagged as an instance method as well. This means that it will work in extended objects:

```
var obj = Object.extended(someVeryDeepObject);
obj.deep('location.address.street', '1600 Pennsylvania Avenue');
```

Or when extending `Object.prototype` (this needs to be explicitly opted into):

```
someVeryDeepObject.deep('location.address.street', '1600 Pennsylvania Avenue');
```

looking at it now, all the suggestions above look strange to me and don't seem very clear if you were to encounter them in code. Definitely open to better suggestions here.

**Comment by andrewplummer** [comment]
I'm flip-flopping a lot on this. One the one hand `get` and `set` are much more expressive as to what they're doing. On the other hand, they are extremely generic for their potentially confusing behavior.

More thinking... maybe it really should do the same as lodash/underscore, which is choose a property with the dots inside if it exists, or go deep if it doesn't. Honestly, that behavior is straightforward enough I think it's unlikely it would be confusing....

**Comment by vendethiel** [comment]
Right. Also, who uses dot-separated properties? :P

**Comment by DylanPiercey** [comment]
+1 for lodash style. If you have both a nested and flat property on the same object you probably need to rethink things anyway.

@vendethiel the only time I can think of is when I flatten objects before submitting them with form data and then unflatten on the server. I certainly can't think of a case where you would want or need both a deep and flat key.

**Comment by andrewplummer** [comment]
Tending to agree with you guys, but want to flesh out one more thing:

To be clear, lodash uses the flat property *if it already exists* and falls back to recursively entering the namespace. However I'm wondering if this is really very useful, or if completely ignoring the flat property is better. Keep an open mind here and imagine that you're working in some crappy code that happens to use both flat and nested properties and you can't do a damn thing about it :)

```
get(obj, 'a.b.c');
```

Let's say this is returning `obj['a.b.c']` and shadowing what you really want to get at, which is `obj.a.b.c` (which is exactly what `_.set` in lodash would do). Your alternative here is to simply use the standard JS notation. However if you're not sure if the namespace exists, you'll have to do something like this: `obj.a && obj.a.b && obj.a.b.c`. 

OK, not too bad, but what about setting a variable on the same namespace? `set(obj, 'a.b.c', 'foo')` would set the flat property, so that's no good. If you weren't sure the namespace exists, you would have to do something quite ugly:

```
 (obj.a || (obj.a = {})) && (obj.a.b || (obj.a.b = {})) && (obj.a.b.c = 'foo');
```

This nearly unintelligible piece of code is just about the most concise you can get without writing your own recursive function. So if this edge case were to happen, you would be kind of stuck. So what if the method *always* recursed into namespaces when it finds a `.`?

```
get(obj. 'a.b.c');
```

Let's say in this case you *want* to get at `obj['a.b.c']`, but it's returning the deep property instead. Well in this case you can simply use standard JS syntax `obj['a.b.c']` with no fuss. Always going deep would make these methods more straightforward with less special cases to cover, so I'm leaning toward it... what do you guys think?

---------------

Last question, what happens if the namespace already exists?

```
var obj = { a: 'b' };
get(obj, 'a.b.c'); // What gets returned here?
set(obj, 'a.b.c', 'foo'); // What gets set here?
```

Lodash will return `undefined` for `get` and ignore `set` completely. Is that best? Is there a use case for recursively going in but stopping when the namespace is not `undefined`? In the example this would mean returning `b` for `get` ... for `set` I'm not sure what would happen... Also an error could be thrown...

**Comment by andrewplummer** [comment]
OK more developments here. For reasons maybe a bit too complicated to go into here, `get` and `set` cannot be set on `Object.prototype`. Sugar does not modify `Object.prototype` by default, but there is a mode that allows type checking methods (`isNumber`), etc and hash methods (`keys`, etc) to be opted-in. It's a bit "at your own risk" but it does add value. There are essentially two ways to handle this:

1. Simply don't allow the method on on the prototype.

The static method would still work, as well as on extended objects:

```
Object.get(obj, 'prop');
var extended = Object.extended(obj);
extended.get('prop');
```

2. Rename the methods.

Either by adding to both:

```
Object.getProp(obj, 'prop');
Object.setProp(obj, 'prop', 'val');
obj.getProp('prop'); // Note this won't work normally
obj.setProp('prop', 'val'); // Note this won't work normally
```

Or making a single method that acts as both a getter and a setter as suggestion above:

```
Object.prop(obj, 'prop');
Object.prop(obj, 'prop', 'val');
obj.prop('prop'); // Note this won't work normally
obj.prop('prop', 'val'); // Note this won't work normally
```

Personally I'm leaning toward simply forbidding it on `Object.prototype`. This mode of usage isn't meant to be standard anyway and extended objects are still available, so this seems to be the cleanest way.

**Comment by andrewplummer** [comment]
One more idea I'm poking about with:

```
set({}, 'foo.0', 'bar');
```

Should this be `{foo:{0:'bar'}}` or `{foo:['bar']}`? By default it would be the first, but I can see the utility in constructing arrays. Lodash it seems always constructs arrays when the keys are numeric, but I think that might be obtrusive if you have an object of models by ids:

```
set({}, 'users.993425.name', 'Harry');
```

If you were constructing this for the first time, the result would be a sparse array instead of an object. If you were to JSONify it, the result would be `{"users":[null,null,...,null,null,{"name":"Harry"}]}` (`null` 993425 times). I definitely think this is bad. One possible way to do it is construct an array instead of an object for the namespace *only* if the index is `0`. This could be useful for iterating, as the first index should always be `0`. After the array is created it will always remain an array, so any subsequent numbers would still remain array indexes.

Another possibility is to have some kind of escaping like `"foo.'0'.bar"`, but I think this is convoluted.

**Comment by andrewplummer** [comment]
OK, got started laying the groundwork for this. Going with `Object.get` and `Object.set` for now and not allowing mapping to `Object.prototype`. For now going with most of what I mentioned above:

- No falling back to flat keys. If there's a dot, we go deep.
- `set` will throw an error if an intermediate namespace is a primitive. This will happen anyway if strict mode is supported by the browser and you try to set a property on any primitive, so this is the best way I think (note that lodash will just bail).
- Not doing any of the array creation trickiness for now.

Also this "dot syntax" will be enabled for array methods that implement mapping shortcuts:

```
arrayOfDeepObjects.map('location.address.street');
```

This turned out to also include the following methods:  `Array#unique`, `Array#groupBy`, `Array#min`, `Array#max`, `Array#least`, `Array#most`, `Array#sortBy`.

Some might not be super useful but I definitely think some are! Imagine sorting that same array:

```
arrayOfDeepObjects.sortBy('location.address.street');
```

**Comment by andrewplummer** [comment]
Bordering on spam now... FYI I also added this deep matching ability for `Function#memoize` which is new to Sugar and takes a hash function that this string is a shortcut for. Think of this as similar to `Array#unique`:

```
arrayOfUsers.unique('path.to.deep.user.id');
```

With huge objects, this is a shortcut so that `unique` doesn't have to recurse through all properties (which is expensive) to determine uniqueness. You instead pass it a path that is guaranteed to be unique. It turns out this translates to `memoize` as well. Example:

```
var fn = fetchUserData.memoize('path.to.deep.user.id'); // some expensive operation
fn(user1);  // fetches
fn(user2);  // fetches
fn(user3);  // fetches
fn(user1);  // cached!
```

The argument is basically a way to determine what a "unique call" to the memoized function is. Anything that is not unique has it's return value cached and returns that on subsequent calls. Usually this argument to `memoize` is a function, but now deep matching can very cleanly make a shortcut to pulling properties out of the first argument to determine unique calls. This should have a lot of use (and very trivial to accomplish now).

**Comment by DylanPiercey** [comment]
@andrewplummer I actually like lodash's approach to the array problem, they use `user.addresses[0]`.

Thanks for your work on this by the way; when used in the entire library it can create many conveniences.

**Comment by andrewplummer** [comment]
That's interesting but I kind of don't like it. In addition to not looking as good (which is my subjective opinion, so it shouldn't count for much), it sort of shoehorns accessing properties with `[]` to mean "arrays" when semantically there's no difference between that and the dot operator (here it's *only* serving to create new arrays when the namespace doesn't exist). I can think back to a long time ago when I was confused about the difference and if I saw this I would probably have though "ok `[]` is an array thing" which would have added to my confusion. Sorry, I know this might seem like overthinking, but there's SO many different parts to Sugar... preventing confusion by adding new concepts or DSL (especially if it applies to only one method) is something that's really important to me.

In addition it would be significantly harder to implement, which would likely impact performance (right now it's a very simple `split` on `.`. Anyway if this really does become an issue for people, then I (grudgingly) agree that this syntax is probably the most straightforward. I think maybe we'll get this out in the wild first and if there's huge clamor for it, it can be added with minimal backward compatibility issues.

**Comment by DylanPiercey** [comment]
One other benefit of using the accessor syntax is that it would work well with parsing nested querystrings, or form data. May not be a use case for everyone but can be handy at times.

Another thing that I personally would love is the "push" notation that forms and querystrings have.

```html
<!-- A Form -->
<input name="item[]" value="a"/>
<input name="item[]" value="b">
<input name="item[]" value="c"/>
```

```console
// A querystring
?item[]=a&item[]=b&item[]=c
```

Will both often be parsed into

```javascript
{ item: ["a", "b", "c" }
```

**Comment by andrewplummer** [comment]
Sugar actually does this in `Object.fromQueryString`. However that's a bit different as we're sort of talking about string parsing now no?

However I do kind of see your use case I think:

```
set({}, 'foo[]`, 'bar');
```

The `[]` would be an instruction to append to the end of the array, or create one if it doesn't exist. Fortunately accessing object properties in this way is a syntax error, so this doesn't clash. However if we were to do this you'd have a bit of edge case silliness with crazy object properties like `{'foo[]': 'bar'}`.

You said "another thing" but that was all I got... did I miss anything?

**Comment by DylanPiercey** [comment]
@andrewplummer I think the edge case could be resolved similarly to the `'field.x': 1` where you would always first check to see if the key in question exists, and if so then just set it, otherwise perform the action, be it a deep nested set or a push.

Not sure what you mean by: `You said "another thing" but that was all I got... did I miss anything?`.
My "Another thing" was simply that it would be cool to handle the push notation on sets, and have it act as a "pop" on gets.

```javascript
var obj = { item: [1] };
Object.set(obj, "item[]", 2)
// obj -> { item: [1, 2] }
Object.get(obj, "item[]") // -> 2
```

**Comment by andrewplummer** [comment]
No I think I got it! I thought you were proposing 2 different ideas :)

> I think the edge case could be resolved similarly to the 'field.x': 1 where you would always first check to see if the key in question exists

To be clear I have *not* gone with this behavior for the reasons outlined above (my 9th comment... god there's so many).

**Comment by andrewplummer** [comment]
OK, I have also added deep property support for `String#assign` which is about to become `String#format` (Issue #476). This will now let you do stuff like this:

```
"You live on: {profile.address.street}".format(user);
```

**Comment by andrewplummer** [comment]
Also @DylanPiercey I'm sitting on the fence about your proposal right now but if I do allow `[]` style syntax, I definitely don't want to avoid doing any `pop` operations, as `get` should never mutate the object. It *could* just return the last element, but I'm not sure how useful this would be.

More likely, the `[]` syntax will only be supported for setting. First I don't want to overcomplicate the `get` function which is different and now (as you can see) is going to be used all over the place. Additionally there is no semantic value whatsoever in using `[]` vs. `.` for `get`.

**Comment by DylanPiercey** [comment]
@andrewplummer Sorry, I didn't mean to say that "[]" should be pop in the "get" function. I was meaning that it should simply return the last element in the array. It makes the api a bit my symmetric:

```javascript
var obj = { a: [1] };
var path = "a[]";

Object.set(obj, path, 2); // { a: [1, 2 ] }
Object.get(obj, path); // 2
```

**Comment by andrewplummer** [comment]
Yeah... I suppose so. You could also make an argument that you might want to reuse the same key for setting a property and getting it again later (or the same property on another object).

**Comment by andrewplummer** [comment]
Having a look at this right now and one thing is really irking me about this syntax:

```
set(user, 'profile.names[]', 'Harry');
set(user, 'profiles[].name', 'Harry');
```

The first example is clearly pushing `"Harry"` onto the `names` array, but what is the second example doing? Is it pushing `{ name: "Harry" }` onto the `profiles` array, or is it setting the `name` property of the last *existing* element in the `profiles` array? If it's the latter, then I think this disconnect with the first example could be really confusing. I'm tempted to only allow `[]` at the very end of the last property and be done with it (implementation would be simpler too).

**Comment by vendethiel** [comment]
That'd be cool. I know perl uses a[-1] for the last elem

**Comment by vendethiel** [comment]
Errr, I meant -- I'm fine with "pushing" not working at all even, I'd say. It's cool if it only works as the last elem in the "format string"

**Comment by DylanPiercey** [comment]
+1 to forcing it at the end.
-1 to `-1`, since this would make it hard to set negative indexes.

**Comment by vendethiel** [comment]
I'm not sure there's a need for that, though?

**Comment by andrewplummer** [comment]
> since this would make it hard to set negative indexes.

Well, when I first wrote that I actually meant *only* `[]` and not allowing any index accessors like `[123]`, but I think I'm still wrestling with it a bit... I think there are 2 main arguments for allowing array-style index accessors:

- You would be able to access the property *with* the added hint that if the object does not exist then create an empty array. However, I think that argument is weakened somewhat by the fact that in that case if the index is anything other than `0` you would end up creating a sparse array, which I find very un-compelling as a use case.

- If you know that `user.addresses` is an array then it just "feels" better to access it with `user.addresses[1]` instead of `user.addresses.1` as that's how you would do it in normal JS.


Both kind of weak... arguments against it are:

- Considerably more complex implementation. `.` is a very simple split operation, where `[123]` requires a regex. This is also probably not too major however.

- While `user.addresses[1]` may "feel" better to look at, it's kind of annoying when building the string, for example while in a loop: `'user.addresses[' + i + ']'` vs. `'user.addresses.' + i`.


Also rather small.... If we end up allowing it, both implementation-wise and semantically I think it would make more sense to allow it anywhere in the string. It would be confusing to be able to access `user.addresses[1]` but not `user.addresses[1].street`. However if we do this the major question is what to do with the `[]` push operator in the middle of the string as I outlined above.

Also, while I'm not particularly interested in `-1` syntax either, I have the same question... Is there any reason to ever set a negative index on an array?

**Comment by DylanPiercey** [comment]
@andrewplummer another positive of the array-style access would be that it is easy to set "application/json" encoded form fields on a javascript object.

http://www.w3.org/TR/html-json-forms/

**Comment by andrewplummer** [comment]
Can you give me a more concrete example of how that would look? I think I know what you mean but want to be 100%

**Comment by DylanPiercey** [comment]
A really simple json form parser:

```html
<form>
    <input name="contacts[]" value="Person 1"/>
    <input name="contacts[]" value="Person 2"/>
    <input name="name[first]" value="first"/>
    <input name="name[first]" value="last"/>
</form>
```

```javascript
var form = document.querySelector("form");
var formData = {};

for (var input of form.elements) {
    Object.set(formData, input.name, input.value);
}

formData; //->
{
    contacts: ["Person 1", "Person 2"],
    name: {
        first: "first",
        last: "last"
   }
}
```

**Comment by andrewplummer** [comment]
Ok, here's where we are. First of all I've consolidated `get` and `set` to use the same underlying code (this wasn't easy) so now the syntaxes should be parallel. Added bracket syntax like `[1234]`.

I've also added push syntax. Was quite on the fence about this one as you can use `Object.fromQueryString` instead, but in the end it's a bit simpler (`fromQueryString` is assuming URL encoded strings with `=` and `&` so you would have to build that string and deal with encoding issues).

As a separate issue but related, I've added support for ranges in the bracket notation as well. This means you can do something like this:

```
Object.get('users.addresses[0..1]');
```

And it will return the first 2 in the array. You can go deeper as well to perform a map operation:

```
Object.get('users.addresses[0..1].street.name');
```

All of this syntax is both 1) complex and 2) potentially non-performant, so I sat down and took a lot of time to do this one right. There are a ton of unit tests now on all the various syntax styles. Additionally I've implemented the entire thing using only `split` and `indexOf`, so it's quite fast. Even the additional range syntax simply does a fast `..` check on the string up front, so it takes up hardly any cycles at all.

OK, so to summarize:

-------------

### Big Points

- You can now get or set a deep property even if the namespace doesn't exist (yay!)
- Dot syntax `user.name.first` or
- Bracket syntax `users[0]`
- Mix and match `user.names[0].first`
- Push to the end of an array when setting `Object.set('user.names[]', 'Frank')`
- Access a range of an array `user.names[0..2]`
- `Object.get`, `Object.set` exist as class methods and on extended objects, but not on `Object.prototype` (as mentioned above)

#### Small Points

- If the string contains `.` or `[]` it will *always* go deep for the reasons listed above.
- If the namespace does not exist, `get` will return `undefined`, and `set` will construct it.
- The criteria for what `set` constructs is based on the syntax. If the property is accessed with dot syntax it will use `{}`. If it uses bracket syntax it will use `[]`. This way you can set IDs in an object without worrying about accidentally creating sparse arrays (as noted above).
- If the namespace exists but is a primitive, `set` will explicitly throw an error for consistency (as browsers in strict mode would anyway). It will *not* do something strange like overwrite the namespace.
- Negative array indexes will be treated as being from the end of the array when bracket syntax is used. That means that `set` with `[-1].name` will set the `name` property of the last elemenet in the array. However if for some bizarre reason you must have negative indexes on your array, then can still be set by using dot syntax `foo.bar.-1.name`.
- Push syntax `[]` is *only* supported for `set`, as `[]` essentially means the last element of the array + 1, not the last element. For the last element use `[-1]` instead.
- An interim `[]` in a key such as `users[].name` will construct the namespace just like normal dot syntax would. In effect it will push an object `{name: '...' }` onto the array. In the same way `users[][0].name` will create an array (instead of an object) that will be pushed onto the `users` array.

- Methods that now support this new sytnax are: `Array#unique`, `Array#groupBy`, `Array#min`, `Array#max`, `Array#least`, `Array#most`, `Array#sortBy`, `Function#memoize`, `String#assign`.


That's it! This will land in 2.0.0 (hopefully soon, this was one of the last holdouts).

**Comment by vendethiel** [comment]
That looks pretty amazing. Looks like some other tools in other languages, like [clojure's specter](https://github.com/nathanmarz/specter/), say. Which makes me think this could be splitted out as a separate plugin/lib..

**Comment by DylanPiercey** [comment]
@andrewplummer this looks great. I like the slice/mal syntax as well. Curious though if you could do something like `users[..]` and copy an array?

**Comment by andrewplummer** [comment]
@vendethiel 2.0.0 will have a much better system not only for plugins but also a build system for building easily making one-off packages/plugins... Can definitely have a look if there's a demand.

@DylanPiercey Yes! Leaving off the first digit assumes `0` and the last digit assumes the end of the array, so `[..]` effectively performs `arr.slice(0, arr.length)`

**Comment by vendethiel** [comment]
So many notifications :). Nice cleanup all 'round.
