### ISSUE TITLE
Is it really necessary to escape hyphens?

### ISSUE THREAD

**Issue by bucaran** [andrewplummer/Sugar#477]
Just wondering. Also have a look at what [SO](http://stackoverflow.com/questions/9589074/regex-should-hyphens-be-escaped) has to say about it. 

Something like this should do it. Trivial of course:

```js
/([\\\/\'*+?|()\[\]{}.^$])/g
```
or

```js
/([.*+?^${}()|\[\]\/\\])/g
```
Do you want me to fork it and PR the edits?

**Comment by andrewplummer** [comment]
Hmmmm... I see your point, however what if someone wanted to escape all characters *inside* a character class like this:

```
new RegExp('[' + RegExp.escape(str) + ']');
```

In this case the escaping would not properly work as described I think....

**Comment by andrewplummer** [comment]
(granted that's probably not a common use case)

**Comment by andyhu** [comment]
Maybe we could think the other way around. If we escape hyphens, is there any edge case that it will make something wrong? If not, I would agree that we should escape it

**Comment by andrewplummer** [comment]
This should not be an issue. '-'.match(/-/) and '-'.match(/\-/) both match the hyphen properly.

More about this issue here: http://stackoverflow.com/questions/9589074/regex-should-hyphens-be-escaped

**Comment by andrewplummer** [comment]
Hi, not sure what the hell I was saying in my last comment... the "match" comment was the exact same thing. In any case yes I think we need to escape for the reason written above. Hyphen does have special meaning in regexes, just not in all contexts. However since we don't know what context it will be used in we should escape, otherwise it will cause issue. Going to close this and will also write a test to this effect:

```
it(RegExp.escape('[A-Z]')).shouldEqual('\[A\-Z\]');
```
