### ISSUE TITLE
Memoize for functions with parameter matching

### ISSUE THREAD

**Issue by mkhanal** [andrewplummer/Sugar#486]
Looks like sugar lacks a memoization mechanism which also checks for parameters.
Right now throttle and once achieve this, but they do it even when the parameters are not same.

**Comment by andrewplummer** [comment]
`Function#once` is Sugar's memoize equivalent. Is there something specific that it's missing for you?

**Comment by mkhanal** [comment]
*once* does not take in considerations the parameters passed.
This is very well handled by underscore and lodash libraries.

An example of the expected memoization function :

suppose my function is 

```javascript
var process = (function(param1, param2) {
    //some action 
}).memoize()
```

then 
```javascript
    process(1, 'abc')
```

and
```javascript
    process(2, 'def') 
```

are different method invocations and both should be executed as the parameters differ. 

however,
```javascript
    process(1, 'abc')
```

and
```javascript
    process(1, 'abc')
```

are same and should be executed only once returning the same result.

**Comment by andrewplummer** [comment]
It's a good point. Will have a look at this.

**Comment by andrewplummer** [comment]
So, having another look at this now... I was keen to make this work identically to Underscore, however I'm wondering if that's optimal. Go to the [Underscore home page](http://underscorejs.org/) and do this in the console:

```
var process = _.memoize(function(n, m) {
   return n + m;
});
console.log(process(1, 'abc'));
console.log(process(2, 'def'));
console.log(process(1, 'def'));
```

The final call will be cached and return '1abc' due to the fact that Underscore's default hash function only cares about the first argument to the memoized function. To me this doesn't seem like an intelligent default... the default behavior has a similar issue to the one raised in this ticket. I would rather see the default hash function take all arguments into consideration so that *every unique call* to the memoized function is cached.

This raises another question, however... if objects are passed into the function, then a simple toString will return '[object Object]' so subsequent calls with different objects will never be called.

This is a tricky problem, but I think I have a nice solution. Sugar already has an internal `stringify` method for exactly this purpose. It recursively walks the object and stringifies it for use in a hash, etc. As you might expect, this can be an expensive operation, but it's highly optimized (uses `typeof` whenever possible which is much faster than a class check, etc), and handles edge cases like `-0` and cyclical objects. Calling this on the arguments object could be the default hashing function. This way any unique arguments to the memoized function (including objects) would result in a unique call, and the result would be cached. I expect that unless you're using extremely large/deep objects, the time required to stringify the arguments object would be trivial compared to whatever function you're trying to memoize here.

Lastly, just like underscore you could pass in your own hashing function if performance is in fact a concern. 

This would keep a nice parallel with `Array#unique` which also allows you to pass a hashing function when you have an array of objects for which you already know the unique key.

What do you think?

**Comment by andrewplummer** [comment]
One more thing.. now that this is no longer only necessarily calling the function "once", it seems that the name is no longer appropriate... It seems to me that the name should also become `memoize` to stay in line, and `once` should be flagged for deprecation... what do you think?

**Comment by mkhanal** [comment]
I agree to your point of once no longer makes sense in this case. But I've used once in a lot of places where I need to call a function as an initializer which needs to be called only once. Instead of using a flag that says if this operation has been performed earlier or not, I just use once on the function. 

Coming to the more important discussion on how to implement memoize, it would be pretty awesome if the objects can be treated as objects/variables without converting to strings. Javascript's '==' should be a very good candidates for comparing two objects or parameters passed instead of using toString method as a starting point. For equating more complex objects like JSON structures, or function references (if you're doing functional programming in javascript), I think we need to create a utility for object equals first, and then we can base our parameter comparison logic. 

A good starting reference point might be the implementation that angularJS uses for its equals method. Its open source nature means that we can open it up and view its implementations. What do you think ? 
We can work on this together if you need some help or you're in time crunch.

**Comment by andrewplummer** [comment]
Wow I was just sitting down to work on this... :)

Agreed about once. For that reason maybe we leave it as a minimalist memoize for one-off functions.

Concerning memoize, as I was saying the "utility for object equals" already exists in Sugar, that's why it makes so much sense to leverage it here.

**Comment by mkhanal** [comment]
:+1:

**Comment by mkhanal** [comment]
Hey Andrew,
Any update on this ?

**Comment by andrewplummer** [comment]
It's coming! Sorry, there's been some big delays recently but definitely on the way!

**Comment by andrewplummer** [comment]
OK! This has now been checked in! Will be going out next release.
