### ISSUE TITLE
1.4.1: Date.isThisAny() fails in Opera Mini

### ISSUE THREAD

**Issue by ermouth** [andrewplummer/Sugar#496]
Methods `.isThisYear`, `.isThisWeek`, `.isThisMonth` throw error in Opera Mini on at least iPhone. Method `.isToday` and similar work fine although.

**Comment by andrewplummer** [comment]
Thank you for this report (and sorry it took so long).

I would love to look into this issue, but debugging seems basically impossible for Opera Mini, as actual rendering/execution isn't performed on the client, no? If you have a good way to debug this I'm all ears.

**Comment by ermouth** [comment]
Sugar is perfect, so you can visit issue page once a year – and see nearly no changes, so no need to sorry )

Debugging Opera-Mini is a pain. The only more or less reliable way is using `server:console?your.url.goes/here` to see console. So debugging is just going step by step, reloading page and reading messages.

Please note, that OM console is unable to show objects in readable way, they all look like `[object Object]` in printout.

**Comment by andrewplummer** [comment]
Ok wow I guess that's the only way. I'll see what I can set up on the site and then have a look.

**Comment by andrewplummer** [comment]
OK I've managed to set up a way to debug this... lots of fun.
It seems that the main cause of the bug was the modulo operator on non-numbers:

```
undefined % 1; // -2147483648
NaN % 1; //  -2147483648
1 % undefined; //  -2147483648
```

Seems to produce something ridiculous (`MIN_SAFE_INTEGER`??). There was a critical path in the date code that ended up being `undefined % 1`, so this was skewing all dates. I've fixed the issue and also swept through the entire codebase for other possible modulo bugs. This particular bug should be OK now but it's pretty much impossible for me at this point to run the unit tests on OM, so might have to think about that one going forward.

**Comment by ermouth** [comment]
Wonderful!

> Seems to produce something ridiculous

Modulo produces ridiculous results in other browsers also. -10%3 >> -1, but valid result is 2. So to get arithmetically valid result (num).mod(div) should be smth like (num % div + div) % div. Got a lot of pain from it once.

**Comment by andrewplummer** [comment]
Yikes... sounds crazy. Anyway I'll have another more comprehensive check when I have more time later.

**Comment by andrewplummer** [comment]
Note here that I did a final sweep of modulo operators on `undefined` just before releasing 2.0.0 to avoid this issue elsewhere. Will make sure to continue this in the future as well!
