### ISSUE TITLE
How to create date locales

### ISSUE THREAD

**Issue by Boycce** [andrewplummer/Sugar#511]
Hey there, 
I almost grasp the logic that is created by the regex inside locale strings, but need a little help. 
Could someone please explain to me **how** each entry is matched.

e.g. How is each entry matched in 
`numbers: ein:|e|er|en|em,zwei,drei,vier,fuenf,sechs,sieben,acht,neun,zehn`
https://github.com/andrewplummer/Sugar/blob/master/lib/locales/de.js

My objective is to build date locales off unicode CLDR during my build process.
http://www.unicode.org/repos/cldr-aux/json/26/main/de/ca-gregorian.json

**Comment by andrewplummer** [comment]
Hi, yes this is a very deep part of locales and isn't documented as well as it could be.

The best way is to just follow the example of other locales as you have already discovered.

For ordinal tokens like `weekdays`, `months`, `units`, `numbers`, and `src` in `modifiers`, there is a simple system that's mostly similar to regexes. `|` is a token for alternation just as regexes. By itself it would end up identical to a regex in the source. `:` is just a marker for a base to set it as fixed before alternation with `|`.  So for example:

```
figur:e|ed|ative|atively
```

would match `figure`, `figured`, `figurative`, and `figuratively`. It would translate into the regex:

```
figur(e|ed|ative|atively)
```

there is also `+` as well, which does is like `|` when `|` is already being used in more complex tokens (it does a split on `+` before processing the inner tokens).

Why all the fanfare instead of just using straight regex tokens concatenated together? Looking back on the code now it seems like a good point. Mostly this seemed more straightforward in some complex cases at the time. Now it seems a bit convoluted, but there you have it...

**Comment by Boycce** [comment]
@andrewplummer Thank-you for your explanation. 

Can you also please explain, if you can, **why** only the number *one* has many alterations in `ein:|e|er|en|em,zwei,drei,vier,fuenf,sechs,sieben,acht,neun,zehn`?

And also **when** a certain entry (e.g. `einen`) gets requested? As i understand `Millisekunde:|n` is called when in singular and plural forms.

**Comment by andrewplummer** [comment]
It's not too tricky, there's no logic about "when". It's simply all possible forms are matched. "one" has many alterations because there are many different forms. That said there are probably many other numerals that are missing patterns but this has been added to on an ad-hoc, per-use-case basis would be my guess (to be sure I'd go back and check the git history, but probably that's what it is).

**Comment by andrewplummer** [comment]
One more thing to add is that this "alternation" is also useful to put certain cases together for later use. For example (sorry for the non-date-related example but imagine the same thing with numerals and tricky case-heavy languages like Russian):

```
eat|ate|eating,read:||ing,go|went|going
```

would produce the following array:

```
['eat', 'ate', 'eating', 'read', 'read', 'reading', 'go', 'went', 'going']
```

Now if you want the present participle form (imagine the "genetive" case in Russian or something the like.. for example if the case were to change depending on if you were saying "5 days from now" vs. "5 days ago") of "read" then you would simply access the 3rd form of the 2nd "set" (2 and 1 respectively in array notation), or [1 * 3 + 2]. Locales like Finnish and Russian are using this system to handle complicated cases in their `relative` formats.

**Comment by andrewplummer** [comment]
Going to close this one out for now. If there's something you feel is missing (other forms of other digits etc). Please feel free to reopen this or another ticket with examples of the missing parts. Thanks!
