### ISSUE TITLE
UTC inconsistency

### ISSUE THREAD

**Issue by simoneb** [andrewplummer/Sugar#512]
I would expect this expression:

``` js
Date.utc.create('July 4, 1776').getUTCOffset()
> "+0200"
```

and this expression:

``` js
new Date('July 4, 1776').utc(true).getUTCOffset()
> "+0000"
```

to evaluate to the same result, but they don't. I would like to understand why.

**Comment by andrewplummer** [comment]
Those methods actually do two entirely different things.

The first is parsing the date AS a UTC date. Think for example if you are passed dates from a server that stores everything as UTC.

The second flags a specific date instance as a "utc date". This means that all other Sugar date methods will use the internal UTC methods (`getUTCMonth` / `setUTCMonth`, etc) instead of normal methods.

These methods are independent of each other, so you can parse UTC dates into "local" date objects, parse "local" dates but treat them as UTC, or do both.

I understand the same naming can be confusing and am open to suggestions about how to make it clearer, whether it's just documentation or otherwise.

**Comment by andrewplummer** [comment]
FYI this is changing in the next version of Sugar. Having so many split methods has come to be cumbersome now. Originally I wanted to do anything to avoid an options object because it was my opinion that simple utility methods such as those in Sugar should not require complicated option parameters to remember. I still think that this is true, but `Date.create` simply has too many possibilities that need to be specified when run. Having `Date.utc.create`, `Date.utc.future` etc just brushes the problem aside, you still need to be aware of how to call it, but doing it in a non-standard way makes it harder to guess. Additionally having them standalone also does not afford a way to mix parameters. So going forward this will be:

```
Date.create('July 4, 1776', {
  utc: true
});
```

Since this is a big change, maybe this is a chance to make clearer the intent. What if we made the parameter `parseAsUTC` instead? Additionally `setUTC` or something like that could also be available to call `utc()` on the date as well on creation. I'm thinking something like this might help avoid confusion here.

**Comment by andrewplummer** [comment]
Ok, in the next version the new options will be `fromUTC` and `setUTC`. `fromUTC` means that the input date will be considered to be in UTC, so the resulting date will be different depending on the user's timezone. `setUTC` is new and will essentially do the same that that `.utc(true)` does now (note this method has also been renamed in the next version to `setUTC` for parity). These options can be used together or separate:

```
var d = Date.create(dateString, {
  fromUTC: true
});
console.log(d.format('{yyyy}-{MM}-{dd} {HH}:{mm}'));
```

```
var d = Date.create(dateString, {
  fromUTC: true,
  setUTC: true
});
console.log(d.format('{yyyy}-{MM}-{dd} {HH}:{mm}'));
```

Both the top and bottom example will produce the exact same date for `d`. However, the bottom example will also set the utc flag, and so `format` will use utc methods like `getUTCHours`. I'm in JST timezone (UTC +9 hours) so for the first example I would see `09:00` for the hours, and `00:00` for the second.

Anyway hopefully this will make things clearer.
