### ISSUE TITLE
Object.isFunction is broken for iterators (and, I'm sure, something else)

### ISSUE THREAD

**Issue by trikadin** [andrewplummer/Sugar#514]
As I see, Object.is<type> is something like this.

``` js
function isType(el, type) {
  return Object.prototype.toString.call(el) === '[object ' + type + ']';
}
```

It's really really bad)

``` js
Object.prototype.toString(Set.prototype[Symbol.iterator]); // "[object Object]"
typeof Set.prototype[Symbol.iterator]; // "function"
```

P. S.

And guys, could you DO NOT rewrite native functions if they exists? Do not rewrite at all.

**Comment by kobezzza** [comment]
+1

**Comment by vendethiel** [comment]
> And guys, could you DO NOT rewrite native functions if they exists? Do not rewrite at all.

They have different semantics, so they should be overriden

**Comment by trikadin** [comment]
> They have different semantics, so they should be overriden

I told about the methods that marked as polyfills in the docs (Array.isArray,Array#filter, Array#map, etc.). Their semantics is totally equals to the native implementations.

**Comment by andrewplummer** [comment]
> It's really really bad)

You're going to have to provide evidence that it's "really really bad", not just assertions. So far, `Object.prototype.toString` is a reliable way to do native checking and avoids a number of pitfalls that can be found with both the `typeof` and `instanceof` operators (these are well documented). Many performance enhancements have been tried and abandoned due to issues with these operators, and right now it's the most reliable type checking method we have (one notable exception here is Arguments objects in older IE, a number of hacks are in place in various libs to do type checking on arguments that are approaching reliable, but there is no 100%). 

Also, there is a problem with your example. You are calling `toString` without passing context, which will always result in `[object Object]`. The point is interesting, however, and I think it's important to keep our eyes on the spec regarding both built-in iterators and generators. If at any point they become something other than "functions", it may be necessary to call into question whether `isFunction` needs to distinguish between normal functions and generators. For now, however, I have tested in all major ES6 enabled browsers and they are correctly returning `[object Function]`.

> DO NOT rewrite native functions...(Array.isArray, Array#filter, Array#map, etc.)

Part of your complaint is valid, but "rewriting" is an oversimplification. First, lets set aside `Array.isArray`, as this method is a true polyfill, and will always use browser implementations if they exist.

In contrast, `Array#filter`, `Array#map`, etc are "enhanced" to allow a first argument other than functions. This allows for shortcuts to mapping functions (for `map`) or matching functions (for the rest). These enhancements are *only* being applied if the first argument is not a function, in which case the native implementation would throw an error. If the first argument is a function, then it will hand off to the native implementation (or polyfill if none exists). In fact, the enhancements simply build functions that can be handed to the native implementation so every time any of these methods are called, they will be in the end handled by the native implementation.

The fact is that these enhancements are one of the most powerful and expressive parts of Sugar, and were not added on a whim. That being said, I can understand the controversy behind doing anything beyond polyfills for native methods, and I think that the complaint here is valid.

The next version of Sugar (2.0.0) will be a major rewrite. The biggest change will be that NO prototypes will touched by default -- this feature will become opt-in. This is a big step in addressing your problem, but after hearing this issue I would like to take another step. Sugar also does not touch `Object.prototype` by default due the major problems there, so this will become an option to the "extend" method. My proposal is that these array enhancements also become their own option. It should look like this (option names are not final yet):

```
Sugar.extend({
  objectPrototype: true,
  arrayEnhancements: false
});
```

This will allow fine-grained control over some of the more "controversial" parts of Sugar and should address your problem nicely. `Object.prototype` enhancement will be off by default. Whether or not array enhancing is as well is something I will have to think about and will depend on what people are expecting, etc. The best part, however, is that this way the enhanced methods will still be available through the global object, like in Underscore, etc:

```
Sugar.Array.filter([1,2,3], 1);
```

**Comment by andrewplummer** [comment]
Also I should mention the above ONLY applies to `every` ,`some`, `filter`, `find`, `findIndex`, and `map` on arrays. Every other Sugar polyfill not only uses native implementations but also is thoroughly tested and should have identical behavior (including the polyfills for the above methods which exist separately from the enhancements).

**Comment by trikadin** [comment]
> Also, there is a problem with your example. You are calling toString without passing context, which will always result in [object Object].

It's just mistype, yes, but... Shit, I don't remember, how did I get It with the right example. I'll try to create working example again :(

> The next version of Sugar (2.0.0) will be a major rewrite. The biggest change will be that NO prototypes will touched by default -- this feature will become opt-in. 

Awesome, thank you, guy) Sorry for my irritable behavior when I wrote this issue. This bug knocked me out)

**Comment by andrewplummer** [comment]
> I don't remember, how did I get It with the right example

Definitely let me know. It raises a good question. I wouldn't be surprised if things still need time to settle around iterators/generators, but if there's spec behavior that makes this tricky as well then it should be handled.

Also if there really are issues around `Object.prototype.toString` for other types, I am open.

**Comment by andrewplummer** [comment]
Closing this for now. Note that `is` methods for primitive types `isString`, `isBoolean`, `isNumber` are returning quickly up front on a `typeof` to help with perf. For the record I'm not doing this with functions as I am not quite ready to part with support for early Firefox versions that incorrectly report regexes as type "function".
