### ISSUE TITLE
"Sunday of next week" while there is Saturday now

### ISSUE THREAD

**Issue by timpler** [andrewplummer/Sugar#519]
It's Saturday now (24th of October) and I'm writing to create date by "sunday of next week". It shows me 25th of October while 25th is "sunday of this week". Sunday of next week should be 1st of November.

Is there any syntax that let's me create next weekday (I mean missing closest given weekday in future and setting it to given weekday that missed)?

**Comment by andrewplummer** [comment]
> Sunday of next week should be 1st of November

Actually, this is as intended. "Next week" is essentially defined as a 7 day period beginning with the next "start of the week", which is Sunday. I realize that this is not the same in all cultures, but the problem is that not only can different cultures have a different start of the week, but they also have different degrees of certainty about which day that is, so it's quite vague. Even in English, the beginning of the week may be "Sunday" or "Monday" depending on who you ask. I'm not sure where you're from, but if you had said "Monday of next week" in English, it would likely be much more certain to be Oct 26th, not Nov 2nd.

Since there is so much vagueness here, Sugar intentionally follows Javascript's convention of making Sunday the first day of the week for all locales, allowing you to override depending on context. If for you Monday should be the first day of the week, then you basically have to do this:

```
var d = Date.create(input);
if (d.getDay() === 0) {
  d.addWeek(1);
}
```

Looking at it now, however. The problem comes because you don't know if `input` is an ambiguous format or not. I could possibly give you a way to override this, however I would hesitate to do this on a locale level because it really depends on who you ask.

But what do you think? Would a way to control the "beginning of the week" solve your problem? I'm assuming that's the issue here, but is that right?

**Comment by andrewplummer** [comment]
Ok please ignore my last comment. This is actually going to be handled in v2.0.0. Each locale will have an independent `firstDayOfTheWeek` that you will be able to customize. The default will be the American Sunday, but nearly all other locales (including other english ones like `en-GB`, `en-CA`, etc) will start with Monday. If you need to override per-locale, you will be able to.
