### ISSUE TITLE
Object.keys throws an error if the 2nd argument is not a function

### ISSUE THREAD

**Issue by juliandescottes** [andrewplummer/Sugar#525]
I've had a small issue with the Object.keys extend, when combined with the following pattern :

```
[obj1, obj2, obj3, obj4, obj5].map(Object.keys)
```

Object.keys will be called with 3 arguments here, which passes the check "arguments.length > 1" (https://github.com/andrewplummer/Sugar/blob/master/lib/object.js#L298). But since the second argument is not a function, fn.call will throw an error right after.

Are you open to a PR to change this behaviour? Checking that the second argument is a function would make this quite safer.
Thanks!

**Comment by andrewplummer** [comment]
Hi, so there's a couple of things about this. First of all a lot has changed since in the new version that's soon to be released. It's still doing only a basic existence check, which will not fix this error, but I'm willing to add a function check to make this stronger. Additionally, 2.0.0 has a new method `lock` that is designed for exactly the kind of situation. It will create a new function that calls the original with a locked number of arguments. So in you're case here you would simply have to do this:

```
[obj1, obj2, obj3, obj4, obj5].map(Object.keys.lock(1));
```

Or, since `Object.keys` is fixed at a length of `1`, just this:

```
[obj1, obj2, obj3, obj4, obj5].map(Object.keys.lock());
```

Either way will work.

**Comment by juliandescottes** [comment]
Hi!

Thanks for the workaround. Although here I can't apply it.

**Comment by andrewplummer** [comment]
Hi. I've applied a fix to the new branch for v2.0.0 for this. Sorry, a lot has changed in the new version so I just went ahead and made this change (also wanted to add unit tests). Anyway thanks for your work on this. Will go out in 2.0.0 (should be quite soon).

**Comment by andrewplummer** [comment]
Update: Note that Object.keys is going to lose its callback in 2.0.0. (preferred method of iteration will be Object.forEach instead), so this problem will go away in any case.

Still will be released soon but taking longer than expected. Thanks for your patience.

**Comment by juliandescottes** [comment]
No longer impacted by the issue as I changed some of my build tasks, but thanks for working on this nonetheless!
