### ISSUE TITLE
Object.equal is slow for shallow-cloned arrays

### ISSUE THREAD

**Issue by ermouth** [andrewplummer/Sugar#527]
Proposal: array equality check better first `===` compare each index pair by pair. If we have an array of objects and its shallow clone `arr.slice(0)`, comparison should be very fast – and now it‘s quiet slow.

UPD. Also discovered, that arrays of different lengths are deep-compared despite it‘s obvious they are not equal.

**Comment by andrewplummer** [comment]
I'm not sure what you mean by "and its shallow clone", or how `arr.slice(0)` would affect comparison.

However, from the first part I think you mean basically "if the object is an array, then compare each element one at time and bail out quickly if not equal". This would indeed improve performance considerably and I think it's a good idea. Doing a `length` check up front would make it even faster.

**Comment by andrewplummer** [comment]
Okay... this was another good one. Honestly I'm embarrassed I hadn't made this change already. `isEqual` was previously relying on stringifying entire objects. This was to handle various important edge cases and also due to convenience as other methods that rely on it for different performance reasons (`Array#unique` most specifically). However this was not good for performance of `isEqual` itself. The approach of stringifying vs. key/value comparison is different, which made this refactor quite tricky, but I think I've got it down to minimal file size increase. However the performance benefit is massive. 1000 iterations of large JSON arrays were previously taking about 300ms to complete. They now take 3ms. Larger structures will see even bigger benefits. Benefits also will trickle into array matching methods that use `isEqual` under the hood. Should be much better... thanks for this!

**Comment by vendethiel** [comment]
I have an use case at $work where I compare arrays of 150k elements (every 250ms... Basically dirty checking done wrong). Have you tried benchmarking it against underscore/lodash?

**Comment by andrewplummer** [comment]
Just ran some benchmarks. It appears to still be roughly 2x slower than Lodash and (interestingly) 3x slower than Underscore. There could be a number of reasons for this. First Sugar recently added the ability to do `isEqual` comparisons on native `Set`. Also, it has an explicit set of types that it will do deep value comparison on (essentially a specific subset of natives). This in itself is a big performance enhancement as it will quickly opt out of performing deep comparisons on host objects like DOM elements, instead comparing them by reference (which you really want to do, as they contain billions of properties and nasty stuff like circular references). As far as I can see from the Underscore code, it doesn't do either of these things. However both of these need to be checked for, so that may be taking some time up.

In any case I'm happy that this puts Sugar in more or less the same ballpark. There are a ton of different cases for this (deep objects, large objects, varying types), and it's very difficult to optimize for all of them at the same time.

I'll keep poking at it after everything goes out.

**Comment by ermouth** [comment]
> thanks for this!

Happy to help, I‘m devoted Sugar‘s fan )

As for 2x difference, that is quite normal fork for different libs of same functionality in JS world, don‘t bother. Even 10x is normal (compare q.js and bluebird, and both are popular).

2x is a modest price for code readability and consistency Sugar provides. In most cases readability is more important, especially taking in account, that for critical sections lodash is too slow also.

So our scenario is ‘use Sugar for all non-CPU critical, and write CPU-bound code by hand’.

**Comment by andrewplummer** [comment]
Closing this but will keep an eye out especially for this method's performance profile. I flagged it as "perf" in the code to keep in mind that perf is especially important in this area :)
