### ISSUE TITLE
Support for Turkish and Norwegian locales

### ISSUE THREAD

**Issue by smurali31** [andrewplummer/Sugar#530]
Is support for these two locales coming soon? We have a product that needs to support these locales.

**Comment by andrewplummer** [comment]
Support for these two locales isn't planned simply because I don't have access to speakers of these locales. If you could procure them we can easily get them in by next release, however. Copying the test and locale files should be quite straight forward.

We already have Swedish so Norwegian shouldn't be too difficult. Turkish sounds like it may be hard however (afaik it's rather unique).

**Comment by ermouth** [comment]
@johs May be you could help with it? Date format templates are quite straightforward and short, for example Swedish https://github.com/andrewplummer/Sugar/blob/master/lib/locales/sv.js

**Comment by johs** [comment]
Ok,
modified the Danish
Johs

**Comment by andrewplummer** [comment]
Looking good! ... I don't suppose I can convince you to add tests as well? :D  I got it started with this commit: f8bd936.

**Comment by andrewplummer** [comment]
Now anyone know any Turkish developers?? :)

**Comment by johs** [comment]
Sorry Andrew,
Sugar is a dependancy on ermouth*s systems that I am using, so I haven’t programmed for it.
johs:)

**Comment by andrewplummer** [comment]
No programming required! Basically have a look at the file I committed. There's english at the end. Just replace the Swedish phrases with Norwegian that matches the english. Don't worry about running anything. As long as the phrases are correct I will make the tests pass!

**Comment by andrewplummer** [comment]
No tests for me? :(

Even text format would be ok... I just need the linguistic skills....

**Comment by cevatkerim** [comment]
@andrewplummer I'll do the Turkish one. Is there a reference file I can follow?

**Comment by andrewplummer** [comment]
Hi! Thanks so much! You check any of the [locale files in the new branch](https://github.com/andrewplummer/Sugar/tree/master-2.0.0/locales), and also [English in date.js](https://github.com/andrewplummer/Sugar/blob/master-2.0.0/lib/date.js#L3411). Lastly, I've [updated the readme as well](https://github.com/andrewplummer/Sugar/tree/master-2.0.0#date-locales).

As I understand Turkish is a bit on it's own linguistically (at least compared to major world languages) so I don't know if theres a good one to branch from but English has the most examples and Russian or Polish have examples of functions being used due to some tricky grammar.
