### ISSUE TITLE
"Modifying natives...isn't it evil?" Missing *Major* Point

### ISSUE THREAD

**Issue by machineghost** [andrewplummer/Sugar#531]
Your "Modifying natives...isn't it evil?" does a great job of explaining the pros/cons of using a native object modifying library.  However, it leaves off a HUGE reason not to do what you guys are doing: separability.

If you start using Sugar today, and then a year from now want to stop (you don't need its features anymore, you find a better library, you quit and someone new inherits your code, etc.), there's no way to separate out the Sugar-using code from the non-Sugar-using code.

If you want to remove jQuery you just grep for `$` in your code, but if you want to remove Sugar you have to go through every feature in the library grepping for (say) `.format(` to see if any code uses the date formatting feature.  And of course there may well be lots of other `.format(` code in your codebase, which means a mass find/replace is impossible.

**Comment by vendethiel** [comment]
I don't see how this is different than with jQuery, really. "You remove $ in your code"? Then... You don't have code anymore? You just rewrite all your code not to use it? Doesn't seem much better

**Comment by andrewplummer** [comment]
Well it's an interesting point (first time I've heard this one). As @vendethiel points out, this isn't necessarily fundamentally any different from a library like jQuery, depending on how you write your code. However, I'll grant that if you're making a concerted effort to put separability first, then you're right that it would be harder than other libraries to do a search/replace on later. I would hardly consider it a "major" issue with the page, however, first because this has as much to do with Sugar being a utility library as it does with extending natives, but also it seems a bit common sense, no? Also, this is setting aside the larger point that if you want to stop using Sugar in the future you're almost certainly going to have to do a rewrite that would require you to look at methods individually anyway. This would be as true of Lodash or Underscore as of Sugar.

At any rate, whether or not you accept this answer I fortunately don't have to take a stance on this one, as v2.0.0 will not modify prototypes by default anyway. If you are putting separability first then you can use methods through the `Sugar` global (just like Lodash or Underscore) and you should be able to search/replace no problem!

**Comment by machineghost** [comment]
>I don't see how this is different than with jQuery, really. "You remove $ in your code"? Then... You don't have code anymore? You just rewrite all your code not to use it? Doesn't seem much better
>This isn't necessarily fundamentally any different from a library like jQuery

Let's say you want to convert from JQuery to a few micro-libraries.  You grep for `\$.ajax` to find the places that will use your new AJAX replacement library.   Then you grep `\$\(.*\)\.on` and `\$\(.*\)\.off`  to find places to replace with your events library, and whatever is left is pretty much what you need to replace with your DOM manipulation library.  Plus, before you even start looking at micro-libraries, you can run those greps and at least know, roughly, how much work it will be to replace jQuery (or whatever it is you want to replace).

Conversely, with native object-manipulating libraries you have to grep for every method you ever remember using.  If you can't remember them all or you inherited the code, you have to grep for every method name in the library.  Plus, if those methods overlap existing methods, you have to determine whether the code is even using the manipulating library, or whether it relies on the original implementation.

So I'm not trying to say jQuery name-spacing itself with `$` magically makes it easy to replace.  What I'm saying is that manipulating native objects makes it far more difficult to even understand when/where/how much your'e using the library, and if you do want to remove it that's more difficult too.

> If you are putting separability first then you can use methods through the Sugar global
This is a critique of the "Modifying natives...isn't it evil?" page.  Obviously using a global variable for Sugar doesn't apply to that page.

**Comment by vendethiel** [comment]
No, that's just plain wrong. When you're using jQuery, you need to check for every call that happened around a `$`. You need to catch `var $x = $(a); $a.hover(...).data(...)`. You need to make sure you're aware of the semantics you're changing, e.g.: `.data` in jQuery doesn't reflect back on the DOM when you change a property. You need to find every place where a jQuery element might have gone to, and find which calls were made on those.
That's equally hard to finding which calls were made on overloaded natives.

**Comment by machineghost** [comment]
So first off, just to be clear, we agree that there are two parts to refactoring a library out of a codebase, and the second part is hard no matter what, right?  In other words you need to replace the old library, and nothing makes that easy, but you also need to *find all the places to replace*, and we're disagreeing over whether using a namespace or not matters for that.

In other words, you're arguing that if you inherit a codebase that uses both jQuery (or any name-spaced library) and Sugar, it will be just as easy for you to find all of the:

     $('#a').remove();

lines as it will be for you to find all of the:

    [1,2,3].remove(3);

lines.  Because both could be: 

    var $a = $('#a')
    $a.remove();

    var a = [1,2,3];
    a.remove(3);

But here's the difference: if I grep for `$(` I will find 0 false positives.  I might not immediately find `$a.remove();`, but unless I'm passing jQuery variables between modules for some odd reason, the definition of `$a` will be just a few lines up (and even if it is passed between modules, there's still `$a = $('#a')` line somewhere I can find by grepping, and then I can follow all the places that use it, in the same module or not).

Conversely, if I grep for `remove(` I'm going to find every `remove` call in the code.  I'll find that `$a.remove()` line, I'll find `document.getElementById("foo").remove(0);`, and I'll find any other use of any method named `remove`.  If there was a native DOM method with the same name (there isn't in this case, but there are for other Sugar methods) I'd even find false positives that are exactly `someArray.remove(`, and I'll have to wade through all of them to find the stuff I need to fix.

But also, and this is the real key, with jQuery or any name-spaced library, I grep *once*, for `$`.  Maybe a few extra times if I'm replacing jQuery with multiple libraries.  With Sugar or any non-name-spaced library I have to grep *for every method in the library* to find all of the places that look Sugar.

That's the difference between the two: `grep $` and following where variables get used vs. `grep add|all|any|at|...` (which is a damn long list in Sugar) and then filtering the results line by line to eliminate the false positives.

**Comment by vendethiel** [comment]
That's if you consider everybody prefixes their jquery variables with `$`, which is far from true. And when you get a false positive, or you miss one, you're going to lose time debugging/finding it.

Etc etc etc. What you want requires flow analysis, and you can't really do that in JS anyway. There are things you can infer, sure, but not all the way, or which types are passed to a function.

**Comment by machineghost** [comment]
Look, at the end of the day you can either be honest with people adopting (the native object form of) your library, or not.  It's your choice.  Nothing I'm going to say can possibly convince you if you don't want to be convinced.

But if you ask some impartial JS programmers, I'm willing to bet that 9 out of 10 will say it's harder to remove a native object library than a name-spaced one.  Being able to grep for a namespace is useful, and you simply can't get that in a native object library.

**Comment by andrewplummer** [comment]
And on that note, I think I'm going to close this one. We could go on, but in the end I think we can agree (I'm willing to at least) that if your *goal* is to make your code as "greppable" as possible, then you would probably choose to go through a namespace instead of augmenting natives. Whether that is a realistic or useful goal, as well as whether or not being able to grep has any practical impact on "separating out Sugar-using code" is a separate issue. However in any case v2.0.0 directly addresses this by introducing a namespace, so I feel confident in calling this issue resolved. (Please continue though, really do enjoy the debate :smile:)
