### ISSUE TITLE
four letter months abbreviations in french

### ISSUE THREAD

**Issue by deddu** [andrewplummer/Sugar#537]
the following fails in February.

```
var today = new Date();
var localestring = today.toLocaleDateString('fr-FR', {year:'numeric', month: 'short', day: '2-digit'} );
var x= Date.create(localestring, 'fr-FR'); 
```

it seems to fail because the abbreviation used by Intl for the month is `févr.` instead of `fév.`.  
Simply removing that extra `r` fixes it. 
There's any way to modify the locale file to account for this cornercase?
I'm trying to wrap my head around the localefiles, do you have any pointer for the documentations to share? thanks

**Comment by deddu** [comment]
[I was able to fix it (hack it) by adding two aliases to the month](https://github.com/deddu/Sugar/commit/5f5f4e63f60919f14b91b83809753282276af038).


I am experiencing similar parsing issues in PT and RU as well.

Identical Issue in RU, 
```
var today = new Date();
var localestring = today.toLocaleDateString('ru-RU', {year:'numeric', month: 'short', day: '2-digit'} );
var x= Date.create(localestring, 'ru-RU'); 
``` 
the localeString has 4 char abbreviation, so I plan to fix in the same way.


In PT It seems to choke because the locale string contains `/`
```
var today = new Date();
var localestring = today.toLocaleDateString('pt-PT', {year:'numeric', month: 'short', day: '2-digit'} );
var x= Date.create(localestring, 'pt-PT'); 
```

**Comment by andrewplummer** [comment]
So it turns out that 2.0.0 gets you mostly there as it has much better month/weekday abbreviations (per-locale now, previously was just truncating at 3 letters). I've added tests with the results from `toLocaleDateString` for all locales.

Additionally I've patched up Russian a bit, as it wasn't as accurate as it could be.

2.0.0 is about to be released any day now, so please hang in there!

**Comment by deddu** [comment]
Awesome! there's anything I can do to help?

**Comment by andrewplummer** [comment]
Well, if you actually do know Russian I was curious whether `фев` is an acceptable month abbreviation, or if it's always `февр`.

Other than that for the release, no it's basically last minute stuff I have to sit down and do. Cranking away at it though...

**Comment by ermouth** [comment]
Since I‘m native Russian speaker, I assure you, that all 3-letter RU locale month abbrevs are absolutely ok.

**Comment by andrewplummer** [comment]
@ermouth Thanks for your help as always :)

So I have added 4-letter format for parsing (actually I replaced it but I need to go back and restore 3-letter as well), but now I have to choose one for formatting. So now, the question is: which is better or more natural?

**Comment by andrewplummer** [comment]
Also would like to know for `сент` vs `сен` as well.

**Comment by deddu** [comment]
Just my two cents, but I would try to stick to what the Intl dateFormat does as much as possible. I guess they are the most "standardized" source of truth at this moment.

**Comment by andrewplummer** [comment]
That does suggest 4-letter, as does most "Russian month abbreviation" resources that I've searched online as well.

**Comment by ermouth** [comment]
Month abbrevs are used in Russian in several ways.

Our common short date format is 31/12 or 31/12/2015. Letter abbreviations are quiet rear in plain texts, and there is no standard for them. Although there are several well-distinguished patterns.

1. Last char in abbrev must always be a consonant, or also two vowels if no period after, but never consonant + vowel. So `янв` or `янв.` is ok, but `янва` is invalid. Although `ноя` is ok but `ноя.` is absolutely not, since `я` is a vowel. 
2. 3-char abrrevs without a period after are bit out of academic rules, but extremely widely used in UIs, so it‘s a de-facto standard.
3. Full months are nearly always in genitive form in dates, not in nominative. Genitive forms like `3 ноября 2015` are much more common than XIX century style `Ноябрь, 3-е, 2015 год` in nominative.
4. 3-char abbrevs with a period are impossible for 6th and 7th months, so they are 3 char without a period or full 4 char form. Contrary, 3rd month, that is also 4-letter long in nominative, is 5-letter long in genitive, so it _can_ be abbreved to `мар.`.

**Comment by andrewplummer** [comment]
Ahh Russian never fails to blow my mind :)

First, I'll go through the points:

1. The part about "period vs no period" being dependent on *vowels* really complicates things because it means that the locale format should know where the periods go, but whether or not to add them is something I'd prefer the user decides.
2. This could help get around #1...
3. Right now all Sugar forms are in the genitive. There are ways to get at the nominative, but it's hacky.
4. Also makes handling periods difficult...

Considering points 1,2, and 4, it seems to me that the best way to handle this is simply to use the 3-char abbreviations with NO period for now. To remind everyone the context this would be only for the `{mon}` format token:

```
date.format('{mon}', 'en'); // -> "Jan"
date.format('{mon}', 'ru'); // -> "янв"
```

Considering use of the period, English of course also has this problem with "May" (shouldn't use a period). Right now you need to use a format string like `'{mon}.'`, but of course that produces `May.` which is strange. The ideal solution is probably to introduce a new token like `{mon.}` which indicates that you want periods when applicable. I don't mind putting in the work for a new token but it means I also have to research periods in month (and weekday) abbreviations for all locales which will take time... The advantage of using 3-letter abbreviations with no period is that it matches what is currently being used, makes intuitive sense given the token, and sidesteps issues with periods.

However, it doesn't match what `toDateLocaleString` uses as @deddu points out. However for this format token I think this should be considered as intentional. I can have a look at the period format later.

Remember that this is only talking about output. Parsing will always work on all formats, 3-letter or 4-letter, period or no period.

**Comment by andrewplummer** [comment]
Given that, how would this be for 3-letter tokens:

```
янв: Jan
фев: Feb
мар: Mar
апр: Apr
май: May
июн: Jun
июл: Jul
авг: Aug
сен: Sep
окт: Oct
ноя: Nov
дек: Dec
```

**Comment by deddu** [comment]
@andrewplummer I am still struggling with the portuguese. (see quick test in previous comment).
parsing from the following format (always from `Date.toLocaleDateString`) fails for a bunch of months:
dd/MMM/YYYY

```
'janeiro: pass
fevereiro, fail
março,pass
abril,fail
maio,fail
junho,pass
julho,pass
agosto,fail
setembro,fail
outubro,fail
novembro,pass
dezembro,fail
```

It seems that the months that have a 3 lett abbreviation identical to the english one manage to be parsed correctly. In the other cases, it is necessary to get rid of the `/` to have a successful parse. I imagine that those are parsing correctly because there's a fall back to the default Date.parse(). But in any case, do you have any pointer for me? I am getting a grasp of the locale files, but it seems to me that the `/` isn't matched correctly by the whitespaces regex. There's a trick for those cases? thanks a lot for all the help.

**Comment by deddu** [comment]
got the PT slashes issue working with the following 
```
    '{date?}\/{month}\/{year?}',
```
I have all the hacks [here](https://github.com/deddu/Sugar/commit/d51268af2c546a428cd6304ce8a3d891d6f9fca5). I can clean all that stuff up and create a PR if you want. in any case those are really ridiculous minor changes. Thanks again Andrew!

**Comment by ermouth** [comment]
> Given that, how would this be for 3-letter tokens

Absolutely ok )

**Comment by andrewplummer** [comment]
Ok, ensured that parsing works for 3-letter and 4-letter in Russian, but formatting uses 3-letter. Will have to re-examine issues with abbreviations and periods later I think.

@deddu I added tests to be 100% sure that the Portuguese months are passing, which they are, but you are saying that they don't pass for the format `dd/MMM/YYYY`. But does this mean that someone in Portuguese would actually write out the month in that format, for example `15/julho/1998`? This wouldn't happen in English. Slashes are for numeric months only, although in the case of `15-Mar-2015` abbreviated text months may appear with non-whitespace separators (which is why you're seeing the abbreviated months parse properly). If the full text month with slashes really is a common format, then the fix you added above is correct (not a hack). You can put it in a PR or I can add it myself.

If there are other issues your hacks are fixing, then I would prefer to see them in the format of "xxxxx fails". Then we can do same as above. I can either review a PR or add myself.

Thanks!
