### ISSUE TITLE
Object.get syntax proposal

### ISSUE THREAD

**Issue by ermouth** [andrewplummer/Sugar#538]
How about extending `Object.get` allowed syntax with `Object.get(object, ["path","to","property"])`? I have real cases where properties has . inside.

To note, I have own implementation that supports extended queries like `$.my.f.getref({x:[{a:1, b:2},{a:2, b:3}]}, ["x","a=2","b"])`, you can check it in console at http://jquerymy.com, it returns `3`. Quite useful for real life, despite the only token supported is `=`.

Also I‘ve discovered, that Object.set ({},"m.1", "x") creates property `m` that is object. Shouldn‘t it be an array?

**Comment by andrewplummer** [comment]
That's actually pretty reasonable as the api can make a clean distinction between strings and arrays... I think it would be simple and useful. Will have a look!

As for the extended queries, that's actually awesome but you'd probably agree it's a little too much for Sugar I think, yes? The last thing I want to introduce is more DSL....

For your last point, that's by design. `[]` vs `.` syntax makes no difference when getting properties (as in JS itself) but for setting properties it's a clean way to make a distinction between objects and arrays that wouldn't be easy to do otherwise, as numbers can be object properties too. Think something like: `Object.set(data, 'usersById.675839.name', 'Harry')`

**Comment by andrewplummer** [comment]
Ok, this is out now in 2.0!
