### ISSUE TITLE
Regression on QML branch: Array.include is not a function

### ISSUE THREAD

**Issue by bgr** [andrewplummer/Sugar#541]
When running code below with build made from `qml` branch using `gulp build:qml`, the following error is thrown: `test.qml:12: TypeError: Property 'include' of object [object Object] is not a function`

```
import QtQuick 2.5
import "sugar.js" as Sugar

Item {
    Component.onCompleted: {
        Sugar.Sugar.extend();

        var arr = [{age:72, foo: 2}, {age:13, foo: 2}];
        arr = arr.exclude(function(el) { return el.age < 18; }); // works
        console.log(arr.length);

        arr = arr.include({age: 99, foo: 9}); // errors
        console.log(arr.length);
    }
}
```

**Comment by andrewplummer** [comment]
Unfortunately I've lost all ability to test Qt anymore as every time I run it it now segfaults on my machine.  Tried it out on another machine with the same results. I've tried installing multiple different times, previous versions, the uninstaller and a lot of other stuff. Nothing seems to work and I don't really have any more time to spend on this issue.

If you have any ideas I'm willing to try them...

**Comment by bgr** [comment]
Welcome to the world of working with QML :) Does it segfault only when running code including sugar, e.g. can you run the following?
```
import QtQuick 2.5

Rectangle {
    width: 200
    height: 200
    color: "red"

    Component.onCompleted: {
        console.log("hello");
    }
}
```
What are the environments you tried on?

**Comment by andrewplummer** [comment]
OK I feel dumb now. I was more or less just giving up on the assumption that the segfault was something internal... it never occurred to me that it was Sugar causing it (I know, right?)

Anyway it appears that there's a few things going on here. First, just accessing the `__proto__` property on `Object.prototype` was causing the segfault...very weird stuff. This property isn't needed so I've simply excluded the token and it's fixed the error.

Additionally `Array#include` is now `Array#add`, which is why that method was failing. Check out the [cautionlog](CAUTION.md) for more breaking changes.

Anyway, rebuilt and it seems to work great!

**Comment by bgr** [comment]
Great that it works! And thanks for pointing me to the cautionlog, didn't occur to me to look at it from 2.0.0 branch.
