### ISSUE TITLE
Possible bug with Locale.getFormats()

### ISSUE THREAD

**Issue by bgr** [andrewplummer/Sugar#543]
I've been having some weird behavior with Dates, in QML with sugar.js built from master-2.0.0 (2e3c81e), that I managed to chase down to the following. Note that I didn't try it in any environment other than Qt 5.5.1 on Windows.

When I run the following code:

```
import QtQuick 2.5
import "sugar.js" as Sugar

Rectangle {
    Component.onCompleted: {
        Sugar.Sugar.extend();
        Date.create('today');
        Date.create('today');
    }
}

```

with sugar.js that has this patch applied:

```
@@ -3103,6 +3103,12 @@ var Sugar = (function() {
       d = cleanDateInput(d);

       if (baseLocale) {
+          console.log("BASE LOCALE");
+          var fms = baseLocale.getFormats();
+          for(var k in fms) {
+            console.log("  ", k, fms[k]);
+          }
+
         iterateOverObject(baseLocale.getFormats(), function(i, dif) {
           var match = d.match(dif.reg), loc, tmp;
           if (match) {

```

the second Date creation will cause a different output, the cached locale it uses seems to be "corrupt":

```
qml: BASE LOCALE
qml:    0 [object Object]
qml:    1 [object Object]
qml:    2 [object Object]
qml:    3 [object Object]
qml:    4 [object Object]
qml:    5 [object Object]
qml:    6 [object Object]
qml:    7 [object Object]
qml:    8 [object Object]
qml:    9 [object Object]
qml:    10 [object Object]
qml:    11 [object Object]
qml:    12 [object Object]
qml:    13 [object Object]
qml:    14 [object Object]
qml:    15 [object Object]
qml:    16 [object Object]
qml:    17 [object Object]
qml:    18 [object Object]
qml:    19 [object Object]
qml:    20 [object Object]
qml:    21 [object Object]
qml:    22 [object Object]
qml:    23 [object Object]
qml:    24 [object Object]
qml:    25 [object Object]
qml:    26 [object Object]
qml:    27 [object Object]
qml:    28 [object Object]
qml:    29 [object Object]
qml:    30 [object Object]
qml:    31 [object Object]
qml:    32 [object Object]
qml:    33 [object Object]
qml:    34 [object Object]
qml:    35 [object Object]
qml:    36 [object Object]
qml:    37 [object Object]
qml:    38 [object Object]
qml:    39 [object Object]
qml:    40 [object Object]
qml:    41 [object Object]
qml:    42 [object Object]
qml: BASE LOCALE
qml:    0 [object Object]
qml:    1 [object Object]
qml:    2 [object Object]
qml:    3 [object Object]
qml:    4 [object Object]
qml:    5 [object Object]
qml:    6 [object Object]
qml:    7 [object Object]
qml:    8 [object Object]
qml:    9 [object Object]
qml:    10 [object Object]
qml:    11 [object Object]
qml:    12 0
qml:    13 -3.4790007051730345e-294
qml:    14 8.174820589400227e-308
qml:    15 1.73231509647014e-270
qml:    16 6.94419123e-315
qml:    17 3.16e-322
qml:    18 function() { [code] }
qml:    19 function() { [code] }
qml:    20 function() { [code] }
qml:    21 function() { [code] }
qml:    22 function() { [code] }
qml:    23 function() { [code] }
qml:    24 function() { [code] }
qml:    25 function() { [code] }
qml:    26 function() { [code] }
qml:    27 function() { [code] }
qml:    28 function() { [code] }
qml:    29 function() { [code] }
qml:    30 function() { [code] }
qml:    31 function() { [code] }
qml:    32 function() { [code] }
qml:    33 [object Object]
qml:    34 [object Object]
qml:    35 [object Object]
qml:    36 [object Object]
qml:    37 [object Object]
qml:    38 [object Object]
qml:    39 [object Object]
qml:    40 [object Object]
qml:    41 [object Object]
qml:    42 [object Object]
qml:    43 [object Object]
```

the output is different every time, sometimes it's characters instead of functions, doesn't smell good.

With the example above, returned dates end up correct nevertheless, but what led me to this was a failing `Date.create('today')` in existing project (which works correctly with old Sugar), because a dozen lines below in sugar.js the following line `set = getFormatMatch(match, dif.to, loc);` actually has `undefined` for `dif.to` and `loc`.

**Comment by andrewplummer** [comment]
Well that's interesting. I've tried it in both browser and node environments and doesn't seem to produce the same result, so it seem to be yet another QML quirk... I'll have to take more time to look into it deeper later...

**Comment by andrewplummer** [comment]
Ok, I found more. The specific line it fails on appears to be here:

```
      [this.cachedFormat].concat(this.compiledFormats) :
```

I should say that mine doesn't produce the exact same result... on the `12` index it simply segfaults rather than returning odd data, so I'm working a bit more blind. Anyway it will apparently segfault on a `concat` operation with `this.compiledFormats`. I've tried a number of things... Making the formats just empty objects still segfaults so it must not have to do with the content of the array itself. Reversing the `concat` operation: `this.compiledFormats.concat([this.cachedFormat])` works but defeats the purpose so need to think of another way. I'll continue to have a look at this as it's a basic feature of Sugar, but starting to consider how many QML bugs must be supported.

**Comment by andrewplummer** [comment]
It appears that `concat` in QML is broken but it's not predictable how or why. I've added a fix that handles this exact issue and happens to be simpler/cleaner in the process, so I think we can go with that. However there are other instances of `concat` being used throughout the date module, which is not to mention elsewhere in Sugar, and I don't think it's reasonable to rewrite all of these.

If another situation with `concat` comes up I think the first thing is to pinpoint the exact issue and report it to them (in fact you might want to do that in the meantime anyway). If they cannot find/replicate/update then it would be best to treat QML in the same way that IE6-8 is treated, which is by adding polyfills for broken/missing methods. The problem here is that `concat` is not even ES5 but ES3. However, it might make sense to write a `concat` polyfill and require that QML users include it (can be even baked into the `qml` task). Anyway I'm getting ahead of myself. The issue may not come up again...

**Comment by bgr** [comment]
Thanks for looking into this. It's working correctly now.

I agree that it's not reasonable to go on a rewrite spree, the code itself is legitimate after all. I will report this on Qt bugtracker, but first I'll try to come up with a standalone example that reproduces the problem, although I have a feeling I won't be able to :)
