### ISSUE TITLE
No RSS feed for releases?

### ISSUE THREAD

**Issue by jikamens** [andrewplummer/Sugar#552]
I used the RSS feed on the old blog to notify me when there were new SugarJS releases. It appears that the blog is gone and the site no longer has an RSS feed for releases. Is there some other mechanism I'm missing to be notified about new releases?

**Comment by andrewplummer** [comment]
I had an RSS feed??? :)

**Comment by andrewplummer** [comment]
Ok so I found the feed...seems it was something I got by default with the old tumblr setup. Will bring it back, but I'm not so knowledgable about RSS... What's best practices here? Before it used to be:

http://blog.sugarjs.com/rss

But now that subdomain is gone, so maybe:

https://sugarjs.com/releases/rss

? Better to have without .xml extension? If you have any tips I'd be happy to oblige, otherwise I'll just use the old Tumblr format and google around a bit for best practices.

**Comment by andrewplummer** [comment]
Also, is "/rss" standard or is there something more........ semantic?

**Comment by jikamens** [comment]
I'm not expert, but I think "/feed" is more generic than "/rss", though I've seen both used in different places.

I think either sugarjs.com/releases/feed or sugarjs.com/releases/rss would both be fine. Note that you should put a meta link in the header of the releases page which shows the URL of the feed. Something like this:

```
<link rel="alternate" type="application/rss+xml" title="SugarJS Releases" href="https://sugarjs.com/releases/feed/" />
```

**Comment by andrewplummer** [comment]
OK! How's this:

https://sugarjs.com/releases/feed

**Comment by jikamens** [comment]
Site is down?

**Comment by jikamens** [comment]
Oh, nope, not down, just http rather than https

**Comment by jikamens** [comment]
Hmm, now just a second later it's back up on https. I'm confused. :-)

**Comment by andrewplummer** [comment]
Sorry bad timing :) I was finalizing the http redirects and had to take the site down in the process... should be back up now!

**Comment by andrewplummer** [comment]
Will close this for now... let me know if there's something more!
