### ISSUE TITLE
Object.isFunction undocumented second attribute

### ISSUE THREAD

**Issue by kobezzza** [andrewplummer/Sugar#555]
**Sugar@2**

I was confused because of

```
[1, 2, function() {}].filter(Object.isFunction) // [] 
[1, 2, function() {}].filter((el) => Object.isFunction(el)) // [function(){}]
```

When i loked to the source of Object.isFunction i found second argument "str" 

```
function (obj, str) {
        // perf: Returning up front on instanceof appears to be slower.
        return isClass(obj, className, str);
}
```

Is it bug or feature?

**Comment by andrewplummer** [comment]
I suppose it's an undocumented feature. `str` can be the result of `Object.prototype.toString.call()`. If this string isn't passed then it will be retrieved. This is just a way to speed up internal checks. Since the internal method is used directly here the argument is available, but it isn't intended to be public.

**Comment by andrewplummer** [comment]
Closing this out for now.
