### ISSUE TITLE
Documentations for older versions of sugarjs

### ISSUE THREAD

**Issue by vegetableman** [andrewplummer/Sugar#561]
Would be great if the lib maintains documentations for older versions similar to `lodash`, as users of the older version `1.4` ( and being restricted to it) , it has become imperative for us to have a resource for reference.

**Comment by andrewplummer** [comment]
This is actually supported now! Have a look at the [site](https://sugarjs.com/docs/). If you click on the vertical "..." at the edge of the menu bar, you can go back to version `1.5.0`. This should be mostly identical to 1.4. There may be a few new methods that don't exist but parameters of existing methods, etc. are all the same. The intention is to do exactly as you're saying and maintain multiple documentation versions going forward. Unfortunately getting the documentation to a maintainable state was part of the changes to 1.5, so that's the earliest version that will be supported, however as stated it should be nearly the same.

**Comment by vegetableman** [comment]
Oh Wow. Thanks @andrewplummer for pointing out the little menu 😀 . `1.5.0` would do as well. Closing this.

**Comment by andrewplummer** [comment]
Yeah... design might be too subtle :)

**Comment by vendethiel** [comment]
Seems like 1.5.0 docs has several rendering issues:

https://sugarjs.com/docs/#/Array/all (seems like version isn't encoded in URL)

**Comment by andrewplummer** [comment]
Ah no, version is stored in local storage, not URL. That's a good idea, however. I'll have a look. Also where are you seeing rendering issues?

**Comment by vendethiel** [comment]
![image](https://cloud.githubusercontent.com/assets/199499/19191848/6ccec798-8ca4-11e6-81ee-33d580ac0262.png)

**Comment by andrewplummer** [comment]
Cool! Thanks for the feedback. I think I've fixed the issues, and I've updated the site to use the version in the URL for previous versions: https://sugarjs.com/docs/#/1.5.0/

**Comment by vendethiel** [comment]
Nice. Can't make sure on mobile atm. I'll check on PC later :)

**Comment by andrewplummer** [comment]
Should be the same on mobile...

**Comment by vendethiel** [comment]
You overestimate what Safari can do...
